dotnet/EntityFramework.Docs

docs/getting-started/aspnet5.rst
ASP.NET beta 8, required by this tutorial is not available in VS2015 RTM. This was not clear to me and the result was that the project wouldn't compile.
Adding a clarification note and a link to instructions on what to install.
@Tratcher @danroth27 PTAL
=> Adding note to clarify that ASP.NET prerequisites

docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relational/SequenceUsed.cs
Changed to "shared.OrderNumbers" to match Sequence.cs and SequenceConfigured.cs samples.
=> Fix in sequence name and schema

docs/modeling/generated-properties.rst
Per discussion on
https://github.com/aspnet/EntityFramework/issues/39551, adding some
notes to clarify that just marking a property as generated is not always
enough to actually get values generated.
=> [SMALL] Clarify value generation may require setup

docs/getting-started/full-dotnet/existing-db.rst, docs/getting-started/full-dotnet/new-db.rst
For Package Manager Console commands you need PowerShell 3.0 or newer.
Adding this to the pre-req section. Doesn't apply to UWP since you need
Windows 10 for that anyway.
Resolves #101
=> :memo: Document min PowerShell version

docs/providers/in-memory/index.rst, docs/providers/index.rst, docs/providers/npgsql/index.rst, docs/providers/sql-compact/index.rst, docs/providers/sql-server/index.rst, docs/providers/sqlite/index.rst, docs/providers/sqlite/limitations.rst
Split each provider out into a separate section to avoid cramming all
the info onto a single page
Introduce a limitations doc for SQLite
@bricelam can you take a look at this one? docs/providers/SQLite/limitations.rst is the only new content, the rest is just restructuring what we already had.
=> Improvements to provider docs

docs/platforms/aspnetcore/getting-started.rst, docs/platforms/aspnetcore/index.rst
ASP.NET will be rebranded to ASP.NET Core... but the current release is
still ASP.NET 5 (so reverting the title/text changes).
Resolves #131
=> Remove ASP.NET Core references

docs/miscellaneous/configuring-dbcontext.rst, docs/miscellaneous/index.rst, docs/platforms/aspnetcore/existing-db.rst, docs/platforms/aspnetcore/new-db.rst, docs/platforms/coreclr/index.rst, docs/platforms/full-dotnet/index.rst, docs/platforms/uwp/index.rst, docs/platforms/uwp/sample/EFGetStarted.UWP/Model.cs, docs/saving/sample/EFSaving/Basics/Sample.cs, docs/saving/sample/EFSaving/ExplicitValuesGenerateProperties/Sample.cs
Fixing various build warnings that had crept in.
C# syntax highlighter doesn't support string interpolation yet, so just
moving to concatenation for the moment.
=> Fix build warnings

docs/platforms/aspnetcore/new-db.rst
The link was broken, giving an 404
=> Fixed broken link to ASP.NET Core RC2 Tools

docs/platforms/uwp/getting-started.rst
Apparently Microsoft.NETCore.UniversalWindowsPlatform 5.2.0 is unlisted on nuget.org. This means `Update-Package` doesn't work and can only be installed with Package Manager Console and adding the `-Version` parameter.
cc @weshaggard @rowanmiller
=> Update instructions for installing .NET Core 1.0 on UWP

docs/platforms/aspnetcore/existing-db.rst
Restarting vs is usually needed in order to run Scaffold-DbContext
-Discussed in more detail here: https://github.com/aspnet/EntityFramework/issues/5376
=> vs restart when Scaffold-DbContest not recognized

docs/modeling/relational/sequences.rst
The original included part of the Order class:
```
public class Order
```
Now it is gone. If the intention was to include the whole class then it should reference lines `5-20` instead.
=> Sequence sample lines reference fix

CONTRIBUTING.md
Replaced the two ASP.NET 5 references in `CONTRIBUTING.md` with ASP.NET Core.
=> Replace ASP.NET 5 references with ASP.NET Core

docs/providers/in-memory/index.rst
There was an extraneous "h" in the `Microsoft.EntityFrameworkCore.InMemory` NuGet package link, which caused it to not work.
=> Fix broken Microsoft.EntityFrameworkCore.InMemory package link

docs/platforms/aspnetcore/new-db.rst
Added a workaround note to reopen Visual Studio in case if Package Manager fails to recognize Add-Migration command. This is a tested behaviour of Package Manager
=> Workaround for Add-Migration command failure

entity-framework/core/miscellaneous/configuring-dbcontext.md
Fixed a typo on line 106.  Changed the word "you" to "your".
=> Fixed typo in configuring-dbcontext.md

samples/core/Saving/Saving/RelatedData/Sample.cs
Adding a related entity issue in  EntityFramework.Docs/samples/core/Saving/Saving/RelatedData/Sample.cs
Object reference not set to an instance of an object.
because blog.Posts is null, not loaded and no lazy loading works
so how to add related:
1) Include(b => b.Posts) required
2) or will be changed in the future ?
[core 1.1.0]
=> Adding a related entity issue in  Sample.cs

entity-framework/core/get-started/netcore/new-db-sqlite.md
In order to better educate audiences, all examples should use CLI tools where appropriate rather than suggesting "replace csproj with".  Where possible in this example, this change does just that.  Additionally, it makes note that a future change is coming to better handle `dotnet` CLI extensions.
This pull request reflects my thoughts described in https://github.com/NuGet/Home/issues/4901
=> Update example to use dotnet add package

entity-framework/core/miscellaneous/configuring-dbcontext.md
The **Create** method of **IDbContextFactory<T>** require **DbContextFactoryOptions** as parameter. So I just added to the document.
Br,
=> DbContextFactoryOptions parameter was missing.

entity-framework/core/get-started/general/efcore1.md, entity-framework/core/get-started/general/efcore2.md, entity-framework/core/get-started/general/index.md, entity-framework/core/get-started/index.md, entity-framework/core/platforms/index.md, entity-framework/toc.md
For preview it was ok to have ad-hoc instructions inline in blog posts as well as listing platforms that e.g. supported .NET Standard 2.0. With RTM we should be moving the useful parts of these into permanent documentation.
=> 2.0 preparation

entity-framework/core/miscellaneous/1x-2x-upgrade.md
At the bottom of [this docs page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/1x-2x-upgrade) the XML nodes are not properly closed, which causes errors when you copy-paste the content to your .csproj file. This PR closes those nodes.
=> Self-close package reference nodes in .csproj xml

entity-framework/core/modeling/indexes.md
A side note: The [link in the site](https://docs.microsoft.com/en-us/ef/core/modeling/indexes) uses the `live` branch but the [contrib.](https://github.com/aspnet/EntityFramework.Docs/blob/live/CONTRIBUTING.md) page says it should be against `master` so I think one of these should change!
=> Add a missing "to"

entity-framework/core/miscellaneous/configuring-dbcontext.md
Since `IDesignTimeDbContextFactory` got changed and `Create` got renamed to `CreateDbContext` this PR fixes the difference in the docs.
=> Change in IDesignTimeDbContextFactory

entity-framework/core/what-is-new/index.md
Changed *EntityTypeConfiguraiton* to *EntityTypeConfiguration*
=> Fix typo in documentation what-is-new/index.md

entity-framework/core/get-started/aspnetcore/existing-db.md
Since some people are developing new applications only needing a subset of the tables that exists in a given database I think it's important to add this to the official documentation even though it's been covered in an [issue](https://github.com/aspnet/EntityFrameworkCore/issues/7930) here on Github and [StackOverflow](https://stackoverflow.com/questions/39065769/can-we-scaffold-dbcontext-from-selected-tables-of-an-existing-database).
=> Add tip for importing specific tables

entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/configuring-dbcontext.md
It seems on docs.microsoft.com anchor tags (<a name="...">) only render correctly (i.e. invisible anchors) if the title that follows them does not have its own id. 
Otherwise the anchor is rendered as visible text and becomes non-functional.
We had two anchor tags that had this problem. One of them had an incoming link from our own documentation, which was fixed in to point to the actual id on the title after it in https://github.com/aspnet/EntityFramework.Docs/commit/79ccf63e2bea86f9d75dd5077ab972b64379ba3c.
There are two more anchor tags on the installation documentation which seem to still be working correctly so I am not touching them.
=> Removing more anchors that are not rendering correctly

entity-framework/docfx.json
This makes docfx.json look a bit similar to ASP.NET docs. Changes were originally in an stale branch from @saldana which shows a more functional breadcrum in preview.
=> Fix breadcrum

entity-framework/index.md, entity-framework/toc.md
- Updating all links in root index page
- Adding external hint arrow ⤤ in root index page
- Removing en-us from the URL in ToC
=> Fixing API reference links in ToC and root index

entity-framework/core/get-started/aspnetcore/new-db.md, entity-framework/core/get-started/full-dotnet/existing-db.md, entity-framework/core/get-started/full-dotnet/new-db.md, entity-framework/core/get-started/install/index.md, entity-framework/core/get-started/netcore/new-db-sqlite.md, entity-framework/core/get-started/uwp/getting-started.md, entity-framework/core/miscellaneous/1x-2x-upgrade.md, entity-framework/core/miscellaneous/cli/powershell.md, entity-framework/core/miscellaneous/connection-strings.md, entity-framework/core/modeling/backing-field.md, entity-framework/core/platforms/index.md, entity-framework/core/providers/sql-server/memory-optimized-tables.md, entity-framework/core/querying/async.md, entity-framework/core/saving/async.md, entity-framework/index.md
- Removes unnecessary en-us from URLs
- Removes unnecessary ?view-efcore-2.0 from URLs
- Points links to documentation on how to install PowerShell instead of different PowerShell downloads
- Use existing docs.microsoft.com links instead of old msdn versions
=> Fixing various links

entity-framework/core/extensions/neinlinq.md, entity-framework/toc.md
I'm not sure if there's some kind of process to add tools to the list (compare #353), but filing an issue asking for sending a PR feels a bit cumbersome. I even don't  know what qualifies a tool being added (hey, it's repo has > 100 stars) here...
Just let me know, if that works for you.
=> Add NeinLinq.EntityFrameworkCore to Tools & Extensions

entity-framework/core/what-is-new/index.md, entity-framework/core/what-is-new/roadmap.md, entity-framework/efcore-and-ef6/choosing.md, entity-framework/efcore-and-ef6/index.md, entity-framework/toc.md
Fixes https://github.com/aspnet/EntityFrameworkCore/issues/9615.
The current roadmap in the product's repo wiki is out of date.
Wanted to see how moving the roadmap to become part of our documentation (alongside the release history) feels and look like.
If we go ahead with this, I will replace the existing pages in the docs with links to the documentation.
Note that here I also moved an explanation about the backlog (that was part of the roadmap wiki page) and the release planning process content here.
I have also removed "critical" and "high priority" lists that as explained in #9615, have become the source of confusion.
Open to suggestions.
=> Experiment: Moving roadmap and other wiki content to docs

entity-framework/core/get-started/aspnetcore/existing-db.md, entity-framework/core/get-started/netcore/new-db-sqlite.md, entity-framework/core/miscellaneous/rc2-rtm-upgrade.md
Fixes #608. At this point these are noise in the tutorials. But I left a note in the page that is about upgrading to 1.0 RTM (although that was originally for the runtime only).
=> Removing project.json notices

samples/core/Saving/Saving/Transactions/CommitableTransaction/Sample.cs
moved openconnection to happen before attempting to enlisttransactions
=> small change to commitabletransaction sample

entity-framework/core/querying/raw-sql.md
Based on query types are now supported and the issue on using types that are not part of the model is now closed.
=> Update raw SQL queries topic for 2.1

entity-framework/core/modeling/owned-entities.md
Fixes #764 and applies minor 2.1 updates.
=> Updating limitations of owned entity types

entity-framework/core/querying/related-data.md
Both the extension methods are specifically designed to be called on a null object without failing and will return the contents of the backing field regardless of whether the lazy-loading object (ILazyLoader or delegate) has been set. Null propagation breaks this because it causes null to always be returned from the getter if the lazy-loading object is not set.
=> Remove null propagation from Load calls

entity-framework/core/saving/cascade-delete.md
Explicitly naming the table and adding breadcrumbs for easier link references in discussion.
=> Sectioned out tables by relationship type

entity-framework/core/modeling/owned-entities.md
Simple edit that bothered me. It made the example in `Querying owned types` a tid-bit confusing, since it wasn't obvious at first that `OrderStatus` was an enum.
=> Added definition for `enum OrderStatus` in later examples.

entity-framework/core/what-is-new/ef-core-2.1.md
ORIGINAL: The optimization requires buffering the results form the subquery.
CORRECT: The optimization requires buffering the results from the subquery.
Unless it meant "to form the subquery, but I find it unlikely. That's why I went straight to PR.
Cheers
=> Fixed small typo 'form' > 'from'

entity-framework/core/modeling/owned-entities.md
Original: "In order to understanding how EF Core tracks these objects, ..."
Fixed: "In order to understand how EF Core tracks these objects, ..."
=> Fix grammar "understanding" -> "understand"

entity-framework/core/managing-schemas/migrations/projects.md
EF Core - Migrations - Separate project
1) When attempting to have migrations in a seperate project, the migrations assembly must contain at least one migration in order for the Add-Migrations command to find the DbContext.
This PR attempts to make the implication of not doing so more clear, as well as making it easier to find why things are breaking when you try to do this for an empty project.
2) Fix a typo in MyStarupProject
=> Signal the implications of not moving migrations

entity-framework/ef6/fundamentals/testing/testability-article.md
"Possible missing Markdown link syntax"
=> C32154: Converting links to links syntax

entity-framework/ef6/modeling/code-first/workflows/new-database.md
This fixes a pair of typos in [the "Code First to a New Database" page](https://docs.microsoft.com/en-ca/ef/ef6/modeling/code-first/workflows/new-database) for EF6.
=> EF6: Fix typos in "Code First to a New Database"

entity-framework/core/miscellaneous/cli/dotnet.md
Hello, @bricelam,
"Unescaped commands are generating conflicts with translated pages:
https://docs.microsoft.com/fr-fr/ef/core/miscellaneous/cli/dotnet#using-the-tools
https://docs.microsoft.com/ja-jp/ef/core/miscellaneous/cli/dotnet#using-the-tools
"
=> V1300944: Converting commands to codebox to avoid localization issues

entity-framework/ef6/fundamentals/install.md
This fixes a typo in [the "Get Entity Framework" page](https://docs.microsoft.com/en-ca/ef/ef6/fundamentals/install) for EF6.
=> EF6: Fix typo in "Get Entity Framework"

entity-framework/ef6/index.md
This fixes a remaining typo on [the EF6 root page](https://docs.microsoft.com/en-ca/ef/ef6/).
=> EF6: Fix typo on root page

entity-framework/core/modeling/value-conversions.md
On the docs site, using `Csharp` results in a language of `Csharp` to be displayed, where `csharp` results in `C#`
So instead of this:
You see this:
=> modify the code example language to improve display

entity-framework/core/get-started/netcore/new-db-sqlite.md
Because we got [a PR](https://github.com/aspnet/EntityFramework.Docs/pull/937) that seems to indicate that it is a bit hidden right now.
=> Making changing the current directory its own step

entity-framework/breadcrumb/toc.yml
That node entry doesn't have a topic associated with it.
If you click on that link on the breadcrumb from pages such as https://docs.microsoft.com/en-us/ef/core/miscellaneous/1x-2x-upgrade, you get a 404.
=> remove broken breadcrumb

entity-framework/core/managing-schemas/migrations/operations.md
reference name and password from CreateUserOperation  instead of having it as vars that are defined and use   TypeMappingSource instead of TypeMapper which is deprecated
=> Use name and password from CreateUserOperation and use TypeMappingSource

entity-framework/ef6/modeling/designer/advanced/edmx/csdl-spec.md
Description of the source issue: Extra space is breaking formatting on ENU site.
=> C42269: Extra space at line 1135

entity-framework/ef6/modeling/designer/advanced/edmx/msl-spec.md
Description of the source issue: Extra space is breaking the formatting on ENU site.
=> C42264: Extra space at line 216

samples/core/GetStarted/AspNetCore/EFGetStarted.AspNetCore.NewDb/Models/Model.cs, samples/core/GetStarted/NetCore/ConsoleApp.SQLite/Model.cs
Modified the EF Code first sample (and thus the tutorial docs) to use ICollection<T> as the other Code first and Db first samples use as well.
=> EF Code first sample model should use ICollection<T>

entity-framework/ef6/fundamentals/testing/mocking.md
Changed `mockSet.As<IQueryable<Blog>>().Setup(m => m.GetEnumerator()).Returns(0 => data.GetEnumerator());` to `mockSet.As<IQueryable<Blog>>().Setup(m => m.GetEnumerator()).Returns(data.GetEnumerator());`
Link to issue: https://github.com/aspnet/EntityFramework.Docs/issues/1027
=> Fixed typo

entity-framework/core/miscellaneous/cli/powershell.md
Scaffold-DbContext will not generate a data model if the table does not have a primary key assigned.
=> Add note about primary keys to Scaffold-DbContext

entity-framework/core/get-started/uwp/getting-started.md
This update corrects what project ends up contiaing the tools package and changes the migrations commands to not require that the console application is selected as startup project. 
I have made a few changes that I think make it easier to complete the tutorial without making mistakes. 
Hello, @rowanmiller,
This proposed file change comes from https://github.com/aspnet/EntityFramework.Docs.es-es/pull/4 .
Could you review this contribution and help to merge if agreed?
=> Fixing UWP tutorial steps

entity-framework/ef6/modeling/code-first/fluent/types-and-properties.md
The character `“` was used instead of `"` in a code exemple. It was then not working properly when copy-pasted.
=> Fix wrong double quote character

entity-framework/index.md, entity-framework/toc.md
New location is https://docs.microsoft.com/dotnet/api/?view=entity-framework-6.2.0.
=> Updated API reference links for EF6

samples/core/QueryTypes/Program.cs
In the code snippet for the database object VIEW, it uses the **Name** field without the alias _**b**_ 
which all other column names have. 
Just to be consistent, I propose adding the alias i.e. **b.Name** as opposed to **Name**.
Lastly, I have capitalized the **from** to **FROM** for readability and consistency as it is a reserved word like JOIN, GROUP BY etc.
=> Modified the VIEW

entity-framework/ef6/what-is-new/upgrading-to-ef6.md
Description of the source issue:
string in (for example) form "**Entity.**EntityState" doesn't render in bold on EN page and asterisks are shown instead. Problem is the dot before two asterisk. Possible fix for this would be moving a dot after two asterisks. 
=> C52739: Asterisk issue

entity-framework/core/querying/related-data.md
Changed
```
This does not mean you will get redundant joins, in most cases EF will consolidate the joins when generating SQL.
```
to
```
This does not mean you will get redundant joins; in most cases, EF will consolidate the joins when generating SQL.
```
for better clarity.
=> Fix grammar for including multiple related entities

entity-framework/core/get-started/install/index.md
This may have been a hyperlink in the past (to something like [this](https://docs.microsoft.com/en-us/dotnet/core/tools/?tabs=netcore2x)).
I've just removed the bracket, but can add in the hyperlink if desired.
=> Removed an extra square bracket

entity-framework/core/miscellaneous/logging.md
Supersedes https://github.com/aspnet/EntityFramework.Docs/pull/1164.
=> EF Core: Note on obsolete warnings for logging API

entity-framework/core/managing-schemas/scaffolding.md
On line 76, the statement used to label the example of the Fluent API's scaffold code had a minor typo.
=> Minor typo on line 76

entity-framework/ef6/fundamentals/performance/perf-whitepaper.md
The blog has been removed, and it didn't add enough that isn't explained here.  
Fixes #1300.
=> Removing reference to App Fabric CAT team blog

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-3.0/features.md, entity-framework/core/what-is-new/ef-core-3.0/index.md, entity-framework/core/what-is-new/index.md, entity-framework/core/what-is-new/roadmap.md, entity-framework/toc.md
We discussed the fact that we want to have breaking changes and new feature descriptions in the documentation which is a more permanent medium than announcements or blogs. 
Here is a proposal for how things can be organized for the 3.0 release.
=> EF Core 3.0 new features and breaking changes

entity-framework/ef6/modeling/code-first/data-annotations.md
Changed spelling of IX_BlogAndRating to IX_BlogIdAndRating.
=> Fixed spelling of IX_BlogAndRating

entity-framework/core/querying/raw-sql.md
See [this issue](https://github.com/aspnet/EntityFramework.Docs/issues/1295) for previous discussion and correspondence with @divega .
The purpose of this update is to clarify that; while both string interpolation and params methods provide protection against SQL Injection, Entity Framework cannot protect your application against non-parameterized dynamic sql.
I believe this update will provide clarification for those making comments on the article. It may also help ensure that people check their stored procedures as well as their EF code when doing security reviews.
=> Suggested improvement to the wording of the warning for the EF Core Raw SQL Document

entity-framework/ef6/fundamentals/relationships.md
The code snippet which shows the Department Model class has bug. I changed this.Course = new HashSet<Course>(); to this.Courses = new HashSet<Course>();
=> Fixed a bug in the Constructor of Department class

entity-framework/core/providers/sqlite/limitations.md
From version 2.2.2 EntityFrameworkCore supports RenameColumn in SQLite provider.
=> Update SQLite limitation md - Support RenameColumn

entity-framework/core/querying/raw-sql.md
Reverts aspnet/EntityFramework.Docs#1372 until we have a clear repro for https://github.com/aspnet/EntityFrameworkCore/issues/13489.
=> Revert "Update Limitations reference Named Mapping"

entity-framework/core/miscellaneous/configuring-dbcontext.md
Mention that `DbContext` cannot be used in parallel on multiple threads and warn, specifically, about async scenarios (since tasks may run in parallel) and dependency injection scenarios (since `DbContext` services are registered with scope lifetime by default).
Fixes #922
=> Update DbContext configuration doc to warn about threading concerns

entity-framework/docfx.json
This will put the same header on the EF docs that is used on the [.NET website](https://dotnet.microsoft.com/) and [main .NET docs](https://docs.microsoft.com/en-us/dotnet/).
Here is an example of this setting in use in the main .NET docs https://github.com/dotnet/docs/blob/master/docfx.json#L108.
=> Add .NET universal header

entity-framework/core/querying/related-data.md
Fix for #1370. Typo - correct to use the NavProp and not the name of the derived class (the existing code snippet doesn't work).
=> Fix wrong NavProp reference.

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
Tracking Issue #14218 - Changed from "alose" to "also".
=> The word was slightly misspelled

entity-framework/core/querying/related-data.md
You can use the `[JsonIgnore]` attribute to ignore serializing a inverse navigation property to prevent a reference loop.
=> Add alternative method for reference loop handling

samples/core/Querying/Querying/RelatedData/Sample.cs
Increase indent for ThenInclude of `author.Photo`, so it matches the other samples (see `MultipleThenIncludes`)
=> Increase indent in IncludeTree sample

entity-framework/core/get-started/netcore/new-db-sqlite.md
Hyperlink from first 'migration' keyword in the document (at very top) is missing. So added hyperlink to 'migrations' for easy access.
=> Added hyperlink to 'migrations' for easy access

entity-framework/core/managing-schemas/migrations/index.md
Using EF Core 2.2 the code sample to get an IMigrator interface `DbContext.GetService<IMigrator>()` doesnt work.
=> Fix call to GetService<IMigrator>()

entity-framework/core/modeling/relational/indexes.md, samples/core/Modeling/FluentAPI/Samples/Relational/ForSqlServerHasIndex.cs
There doesn't seem to be any documentation around this feature, I only discovered it through GitHub issues requesting the feature to be added. 
I also noticed `ForSqlServerHasIndex` has been removed in a breaking change on aspnet/EntityFrameworkCore#12366 and replaced with `HasIndex`, but this still holds for `ForSqlServerInclude`.
=> add ForSqlServerHasIndex sample

entity-framework/core/modeling/query-types.md
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Description: Missing hard break-line before snippet is preventing content to show properly.
=> C113615: Adding break-line before snippet

entity-framework/ef6/fundamentals/async.md
Description: missing spaces at the end of the reported strings created create content misalignment. Kindly consider adding 2 spaces as shown below.
=> C113612: Adding two spaces at the end of list items to avoid issues in live pages

entity-framework/core/managing-schemas/migrations/index.md
- Add note about using different assemblies for the database and startup.
This information would've been very useful to our team if it was mentioned here, and would've saved us a lot of time and head scratching.
=> Update doc on migrations

entity-framework/core/querying/raw-sql.md, samples/core/Querying/RawSQL/Sample.cs
=> Document new FromSql{Raw,Interpolated} methods

entity-framework/core/managing-schemas/scaffolding.md, entity-framework/core/miscellaneous/nullable-reference-types.md, entity-framework/core/modeling/required-optional.md, entity-framework/toc.yml, samples/core/Miscellaneous/NullableReferenceTypes/Address.cs, samples/core/Miscellaneous/NullableReferenceTypes/Customer.cs, samples/core/Miscellaneous/NullableReferenceTypes/CustomerWithoutNullableReferenceTypes.cs, samples/core/Miscellaneous/NullableReferenceTypes/ExtraOptionalOrderInfo.cs, samples/core/Miscellaneous/NullableReferenceTypes/NullableReferenceTypes.csproj, samples/core/Miscellaneous/NullableReferenceTypes/NullableReferenceTypesContext.cs, samples/core/Miscellaneous/NullableReferenceTypes/OptionalOrderInfo.cs, samples/core/Miscellaneous/NullableReferenceTypes/Order.cs, samples/core/Miscellaneous/NullableReferenceTypes/Product.cs, samples/core/Miscellaneous/NullableReferenceTypes/Program.cs
=> Document C# 8 nullable reference types

entity-framework/core/providers/cosmos/index.md
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Description: Missing break-line before snippet is preventing content to show properly.
=> L125172: Adding break-line before snippet

entity-framework/core/providers/sql-server/index.md, entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
System.Data.SqlClient -> Microsoft.Data.SqlClient
Fixes #1815
=> Add 3.0 breaking change note for SqlClient

samples/core/Miscellaneous/Testing/TestProject/InMemory/BlogServiceTests.cs, samples/core/Miscellaneous/Testing/TestProject/SQLite/BlogServiceTests.cs
Use the preferred IANA example.com domain for examples.
=>  Use IANA example.com domain

entity-framework/ef6/fundamentals/relationships.md
I simply found a small typo in the documentation. Nothing major
=> Found a small typo

entity-framework/ef6/index.md
Added relative hyperlink to EF6 providers for easy redirection.
=> Updated hyperlink to EF6 providers

entity-framework/ef6/what-is-new/past-releases.md
At some places dot was used instead of colons- fixed those.
At one line (in the end) a bar character ('|') was present, removed that.
=> Refined documentation by adding and removing few character

entity-framework/ef6/modeling/code-first/migrations/migrate-exe.md
Replace all double quotes (”) by a normal double quote character (").
This makes sure that the commands can be copy-pasted into the command prompt.
Related to https://github.com/aspnet/EntityFramework.Docs/issues/1901
=> Replace all double quotes (”) by a normal double quote character (").

entity-framework/core/modeling/owned-entities.md, samples/core/Modeling/OwnedEntities/OwnedEntities.csproj, samples/core/Modeling/OwnedEntities/OwnedEntityContext.cs
Fixes #1239
Fixes #1400
Fixes #1457
Fixes #1628
Fixes #1629
Fixes #1781
Fixes #1888
=> Clarify some statements in the owned entity types docs

entity-framework/core/miscellaneous/1x-2x-upgrade.md
See @smitpatel's comment in https://github.com/Youssef1313/EntityFramework.Docs/commit/a9a66b1ceab03b30e817d127c5ab39f36682f7a2#commitcomment-35966423
=> Correct some localized links

entity-framework/ef6/fundamentals/connection-resiliency/retry-logic.md
=> Update the guidance for using transactions and execution strategy

entity-framework/core/modeling/relational/fk-constraints.md, entity-framework/core/modeling/relationships.md
Fixes #489
Fixes #1307
Fixes #1315
Fixes #1346
Fixes #1617
Fixes #1658
=> Improve the relationship docs

samples/core/Modeling/FluentAPI/Relationships/OneToOne.cs
Updated the `HasOne` parameter name to be consistent with `HasForeignKey` so as not to cause confusion. Resolves https://github.com/aspnet/EntityFramework.Docs/issues/1626
=> Update parameter name for clarity

entity-framework/core/extensions/index.md
Issue #2000.  Followup of #1864.
Add EFCore.TimeTraveler to the list of EF Core Extensions as well as expand on differences between EFCore.TimeTraveler and EfCoreTemporalTable.
I didn't want to be too verbose here, so I left these details out:
* `EfCoreTemporalTable` exposes the full power of SQL Server Temporal Table history by supporting all available types of temporal queries.  
* `EFCore.TimeTraveler` focuses only on querying for a point in time with `FOR SYSTEM_TIME AS OF`
* With `EfCoreTemporalTable` you query multiple entities from history using JOIN syntax.
* With `EFCore.TimeTraveler` you may use `.Include()`, '.ThenInclude()', and navigation properties to access an entire object graph persisted from the temporal history of multiple tables.
=> Add EFCore.TimeTraveler to the list of EF Core Extensions

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
See https://github.com/aspnet/EntityFrameworkCore/issues/19157
=> Add clarification to design package reference

entity-framework/core/miscellaneous/nullable-reference-types.md
=> Add note on NRTs and backing field configuration

entity-framework/core/modeling/backing-field.md, samples/core/Modeling/FluentAPI/BackingField.cs, samples/core/Modeling/FluentAPI/BackingFieldAccessMode.cs
* Reorganize content based on topics and not convention/fluent API/data annotations, as done in #1669.
* Correct the documentation of the default property access mode (change from PreferFieldDuringConstruction to PreferField in 3.0), and add a note on the behavior change.
* Various other cleanups and improvements.
=> Improve backing field modeling page

entity-framework/core/providers/cosmos/index.md
Very small PR that fixes a typo on the Cosmos DB Provider docs.
=> Fix a typo in Cosmos DB Provider Docs

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
=> Make EF Core 3.1 the mitigation for 3.0 not supporting .NET Standard 2.0

entity-framework/core/what-is-new/index.md, entity-framework/core/what-is-new/release-planning.md, entity-framework/toc.yml
Specifically added text about how to read the backlog and the process for deciding what to patch.
=> Updates to release planning

samples/core/QueryFilters/Program.cs
In the new 3.1, field mapping is changed which is not reflected in docs. updating the doc to highlight it accordingly.
Fix #1961
=> Update Program.cs for correctly showing field mapping

entity-framework/core/modeling/relationships.md
When defining the different terms used, the Foreign key is defined before the Principal key although the former mentions the latter, switching positions might be clearer for the reader
=> Move Principal key definition before Foreign key

entity-framework/core/get-started/install/index.md
ASP.NET Core 3.0 does not automatically reference `Microsoft.EntityFrameworkCore.Design`. I did not mention that this is not necessary on ASP.NET Core 2.2 and earlier as this may confuse customers, and they'll need to add this reference once they upgrade anyways.
=> Remove outdated information

.vscode/extensions.json, .vscode/settings.json
Recommend the [Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack) extension to contributors using VS Code (if it's not already installed). Additionally, configure the most commonly used dev langs in this docset. This helps contributors select the appropriate code fence dev lang when typing 3 backticks. See https://github.com/aspnet/AspNetCore.Docs/pull/16986 for a preview of the functionality.
/cc: @ajcvickers for awareness
=> Recommend Docs Authoring Pack extension and configure dev langs

samples/core/QueryFilters/Program.cs
In #2074, the name of the property "TenantId" was changed to "_tenantId", but the change was not propagated throughout the code, so the sample was not running anymore.
=> Fix QueryFilters sample program

entity-framework/core/modeling/owned-entities.md
in this article yo use [owned entity] and [owned type] interchangeably but in this sentence it's better to use [owned entity] not to make any confusing to user
Suggestion :: to use only one term
=> change [owned type] to [owned entity]

entity-framework/core/saving/concurrency.md
=> spelling set up as setup

entity-framework/core/what-is-new/ef-core-5.0/plan.md
There are multiple GH issues tracking the various components of many-to-many. Previously, only one of them was mentioned here. I have added the rest. Please feel free to adjust/edit as you see fit. (I couldn't find an issue for the configuration sugar)
I have also added additional text to clarify which issues are planned and which are only stretch goals.
=> Update plan.md to clarify many-to-many

entity-framework/breadcrumb/toc.yml, entity-framework/docfx.json, entity-framework/toc.yml
Fixes https://github.com/dotnet/EntityFramework.Docs/issues/2131
[Internal review page](https://review.docs.microsoft.com/ef/core/?branch=pr-en-us-2159)
This PR also updates the master ToC by:
- Removing gerunds, where it makes sense
- Convert titles to sentence case
=> Make breadcrumbs consistent with .NET and ASP.NET docs

entity-framework/core/managing-schemas/migrations/index.md
This updates the documentation to add a from and to usage examples to migration script samples on the Migrations page under the General SQL Scripts section. I believe that this will help new users of EF code-first as there are no examples of its usage in the current EF Core documentation.
=> Documentation Update: Add from and to usage examples to migration script samples

entity-framework/ef6/what-is-new/index.md
Tell customers to make sure projects are in the right order in .sln file to avoid error message.
Fixes #2163
=> Adding warning to EF6 What's New Entity designer support section

entity-framework/core/get-started/install/index.md
as per nuget.org's package description https://www.nuget.org/packages/Microsoft.EntityFrameworkCore, EF Core depends on NET Standard 2.0, instead of .NET Standard 2.1 as originally mentioned
=> fix: EF core depends on .NET Standard 2.0.

entity-framework/ef6/what-is-new/index.md
Docs fix for [EF6 issue 1616](https://github.com/dotnet/ef6/issues/1616).
Say that SDK-style .NET Framework projects are not supported.
=> Docs fix for EF6 issue 1616. 

entity-framework/core/miscellaneous/configuring-dbcontext.md
For Blazor Server hosting model, one logical request is used for maintaining the Blazor user circuit, and thus only one scoped DbContext instance is available per user circuit if the default injection scope is used.
=> Explained Blazor Server specifics for configuring-dbcontext.md

entity-framework/core/miscellaneous/testing/index.md
=> Guidance on testing EF Core apps

entity-framework/core/platforms/index.md
Description: Corrupted character t doesn't show up in the page,
=> L200059: Replacing curly aphostrophe by regular one

entity-framework/ef6/modeling/code-first/migrations/teams.md
There should be an update-database after applying a blank merge before "continue developing"
=> Missing update-database

entity-framework/core/modeling/backing-field.md, entity-framework/core/modeling/keyless-entity-types.md
Fixes #2294 
Updating to say when the `Keyless` attribute became available (also the same info about the `BackingField` attribute).
=> Stating when the BackingField and Keyless attributes became available

entity-framework/efcore-and-ef6/index.md
The doc probably means ".. EF6 to EF Core" instead of ".. EF6 to .NET Core"
=> (AzureCXP) Correct description

.github/workflows/build-samples.yml, samples/core/CompiledQueries/CompiledQueries.csproj, samples/core/Cosmos/Cosmos.csproj, samples/core/DbContextPooling/DbContextPooling.csproj, samples/core/GetStarted/EFGetStarted.csproj, samples/core/Intro/Intro.csproj, samples/core/KeylessEntityTypes/KeylessEntityTypes.csproj, samples/core/Miscellaneous/ConnectionResiliency/ConnectionResiliency.csproj, samples/core/Miscellaneous/Logging/Logging/Logging.csproj, samples/core/Miscellaneous/NullableReferenceTypes/NullableReferenceTypes.csproj, samples/core/Miscellaneous/Testing/BusinessLogic/BusinessLogic.csproj, samples/core/Miscellaneous/Testing/TestProject/TestProject.csproj, samples/core/Modeling/Conventions/Conventions.csproj, samples/core/Modeling/DataAnnotations/DataAnnotations.csproj, samples/core/Modeling/DataSeeding/DataSeeding.csproj, samples/core/Modeling/DynamicModel/DynamicModel.csproj, samples/core/Modeling/FluentAPI/FluentAPI.csproj, samples/core/Modeling/FluentAPI/Keyless.cs, samples/core/Modeling/OwnedEntities/OwnedEntities.csproj, samples/core/Modeling/TableSplitting/TableSplitting.csproj, samples/core/QueryFilters/QueryFilters.csproj, samples/core/Querying/Querying.csproj, samples/core/Samples.sln, samples/core/Saving/Saving.csproj, samples/core/SqlServer/SqlServer.csproj
* Fix solution project reference
* Target netcoreapp3.1 instead of netcoreapp3.0
* Depend on EF Core 5.0.0-preview3 for new annotations
* Fix typo in type name
=> Fixes to samples to make them build, plus Github Action to prevent breaks

entity-framework/core/managing-schemas/migrations/index.md, entity-framework/core/managing-schemas/scaffolding.md, entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/cli/powershell.md
Fixes #2303 
Specify how to use Namespace and ContextNamespace for migrations and scaffolding.
=> Specify how to use Namespace and ContextNamespace for migrations and scaffolding.

entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/cli/powershell.md
Fixes #2337 
Specify how to use Connection for `Update-Database` and CLI equivalent.
=> Specify how to use Connection in Update-Database.

entity-framework/core/miscellaneous/cli/dbcontext-creation.md
Specify that the args param is now used for IDesignTimeDbContextFactory implementations.
=> Args param is now used for IDesignTimeDbContextFactory

entity-framework/docfx.json
[Internal Review - Note that the .NET Nav header has been removed](https://review.docs.microsoft.com/en-us/ef/core/?branch=pr-en-us-2344)
Fixes #2343 
What was updated:
Removed the .NET header value of "MSDocsHeader-DotNet" from "uhfHeaderId" in docfx.json.
=> Remove L2 .NET Navigation Header

entity-framework/core/miscellaneous/connection-strings.md
Fixes #2346 .
Guide people towards the Name= syntax for connection strings.
=> Fix for 2346. Guide people towards the Name= syntax for connection strings

entity-framework/core/managing-schemas/scaffolding.md
Fixes #2357 
Update the docs to state that --namespace and --context-namespace only available in EFCore 5.0.
=> Namespace and ContextNamespace options only available in 5.0

entity-framework/core/modeling/inheritance.md
=> Tweaks to inheritance docs

entity-framework/core/modeling/dynamic-model.md
The code in the sample shows `UseIntProperty` but the explanation refers to `IgnoreIntProperty`, so I've updated this accordingly.
I also removed an extraneous space and swapped a trailing `:` for a `.`. I wouldn't have submitted a PR for just those, but I took the opportunity whilst I was in the topic.
=> Refer to the correct property when discussing IModelCacheKeyFactory

entity-framework/core/managing-schemas/migrations/providers.md
I noticed that "differently" should be "different", but I made a couple of other small change to the sentance. Please let me know if these kinds of changes are appreciated, and I will continue to submit PRs as I read through more of the topics.
=> Fix up wording when discussing MigrationBuilder.ActiveProvider

entity-framework/core/modeling/spatial.md
The Point.CreatePoint() method has two variants:
public Point CreatePoint(CoordinateSequence coordinates);
public Point CreatePoint(Coordinate coordinate); 
It does not support (or no longer supports) a variant that takes two decimals as described in this example. Visual Studio 2019 marks the current version of line 90 as an error.
The decimal values in the example need to be wrapped in a Coordinate object that can be constructed from those values. Then the CreatePoint() method can work as intended.
=> Fix the CreatePoint() example

entity-framework/core/querying/related-data.md
adding "caution" block and example
Fixes #2436
=> Fix to #2436 - Filtered include should also notify users about how it interact with tracked entities

entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/cli/powershell.md
Fixes #2422.  Document that the `-Namespace` and `-ContextNamespace` flags on `Scaffold-DbContext`, plus the `-Namespace` flag on `Add-Migration` are only available in 5.0.0 (and similarly for the command-line equivalents).
Fixes #2405. Document the `-NoOnConfiguring` flag on `Scaffold-DbContext`, also only available in 5.0.0 (and its command-line equivalent).
=> Fix for issues 2422 and 2405.

entity-framework/core/get-started/index.md
Fixes the part of #2335 about defining PMC before first use. Found that there was only 1 case where we were just using the abbreviation without defining it.
=> Fix for 2335. Adding definition of PMC before first use.

entity-framework/core/managing-schemas/scaffolding.md, entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/cli/powershell.md, entity-framework/core/miscellaneous/rc1-rc2-upgrade.md
Fixes #2335 (remaining part). Make sure we reference ".NET Core CLI" where we haven't already defined "CLI" as an abbreviation for that.
=> Making sure we reference .NET Core CLI.

entity-framework/core/extensions/index.md
Mentioning NCache Entity Framework Core Provider as Second level cache. This is thirdparty provider which caches data on distributed environment. This architecture makes in highly available, scalable and reliable.
=> Mentioning NCache Entity Framework Core Provider

entity-framework/core/managing-schemas/scaffolding.md, entity-framework/core/miscellaneous/connection-strings.md
The one in the example was not correct
=> Updated scaffolding named connection string syntax

entity-framework/core/querying/related-data.md, samples/core/Querying/Querying.csproj, samples/core/Querying/RelatedData/Sample.cs
=> Docs for query splitting

entity-framework/core/modeling/shadow-properties.md
Describe the limitation of Shadow Properties in the very first paragraph
=> doc: add limitations

entity-framework/core/miscellaneous/cli/dotnet.md
Fixes #2470 
Mention that the `--connection` option for `dotnet ef database update` is only available from EFCore 5.0.0 onwards.
=> --connection for database update is EFCore 5 onwards.

entity-framework/core/miscellaneous/nullable-reference-types.md, samples/core/Miscellaneous/NullableReferenceTypes/NullableReferenceTypesContext.cs
Thanks @davidroth for suggesting this.
See https://github.com/dotnet/efcore/issues/21608
=> Improve nullability guidance for DbSets

entity-framework/index.yml, entity-framework/toc.yml
Add link to new Blazor Server guidance.
=> Update index.yml and toc.yml to reference new Blazor guidance

entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md
I imagine we should only have version numbers on the right TOC
=> fix header level

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
=> Add replacement for IQueryTypeConfiguration in breaking changes

entity-framework/core/querying/filters.md, entity-framework/core/querying/how-query-works.md, entity-framework/core/querying/related-data.md, entity-framework/core/querying/tracking.md
Couldn't help myself before I start writing more content here
=> Fix some issues

entity-framework/core/querying/related-data.md, samples/core/Querying/Querying.csproj, samples/core/Querying/RelatedData/Sample.cs, samples/core/Querying/RelatedData/SplitQueriesBloggingContext.cs
* Document the new global split query configuration and AsSingleQuery
* Refactoring of the section for better readability and some updates
Continues #2479
=> Update single/split query docs

entity-framework/core/querying/raw-sql.md
I recently experienced a peculiarity in `FromSql()` in a netcore-2.1 project as described in the commit. I think this may be worth documenting, but I understand if this should be opened as an issue in the EF Core project instead.
=> Ordering Caveat in FromSql

.vscode/settings.json, entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
Fixes #2526
Fixes #2585
Fixes #2225
Fixes #2546
=> Add some breaking changes

entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/cli/powershell.md, entity-framework/core/miscellaneous/testing/index.md, entity-framework/core/miscellaneous/testing/testing-sample.md, entity-framework/core/modeling/value-comparers.md, entity-framework/core/providers/sql-server/azure-sql-database.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md
View is like product version.
By not specifying the view, it will go to the latest version automatically.
In some cases we need to target particular view there we need to add &preserve-view=true
New warnings everyday!
=> Avoid unnecessary views in URL to other product docs

entity-framework/core/what-is-new/ef-core-3.x/breaking-changes.md, entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
Add a note for keyless entities with only optional properties
Fixes #2471
Fixes #2491
=> Add Cosmos breaking changes

entity-framework/core/managing-schemas/migrations/applying.md
Found a typo in the 'Applying Migrations with EF Core' document.
https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli
I have done the fix in this pull request.
=> Fixed a typo in the 'Applying Migrations with EF Core' document.

entity-framework/core/managing-schemas/migrations/applying.md
=> Tweak wording on migrations warning

.openpublishing.publish.config.json, entity-framework/core/miscellaneous/context-pooling.md, entity-framework/core/miscellaneous/dbcontextpool.md, entity-framework/toc.yml
Fixes #501, Fixes #1181
[Internal review URL](https://review.docs.microsoft.com/en-us/ef/core/miscellaneous/dbcontextpool?branch=pr-en-us-2662)
=> New doc on context pooling

entity-framework/core/index.md
First pass at #2106
[Internal review URL](https://review.docs.microsoft.com/en-us/ef/core/?branch=pr-en-us-2668#ef-orm-considerations)
Apply MS style guide such as split up long sentences, use "For more information", ect.
Linking to the `## EF ORM considerations` section will be beneficial to EF docs in other repositories.
=> Add start of ORM considerations

entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
=> Document IndexBuilder.HasName breaking change

entity-framework/ef6/fundamentals/install.md
Added a hyperlink to 'Entity Framework Tools for Visual Studio' for easy redirection.
=> Added hyperlink

entity-framework/core/providers/sqlite/limitations.md, entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
=> Document SQLite idempotent script limitations

entity-framework/core/managing-schemas/migrations/managing.md
Warning about losing custom operations when resetting/squashing migrations.
=> Add warning about lost custom operations

entity-framework/core/modeling/data-seeding.md, entity-framework/core/modeling/relationships.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md, samples/core/Modeling/FluentAPI/FluentAPI.csproj, samples/core/Modeling/FluentAPI/IndexName.cs, samples/core/Modeling/FluentAPI/Program.cs, samples/core/Modeling/FluentAPI/Relationships/ManyToManyPayload.cs, samples/core/Modeling/FluentAPI/Relationships/ManyToManyShared.cs
=> Add documentation for many-to-many relationship configuration.

entity-framework/core/modeling/inheritance.md, samples/core/Modeling/FluentAPI/TPTConfiguration.cs
=> Add documentation for TPT configuration.

entity-framework/core/providers/sqlite/functions.md, entity-framework/core/providers/sqlite/spatial.md, entity-framework/toc.yml
=> Document SQLite function mappings

entity-framework/core/get-started/xamarin.md, samples/core/Xamarin/EFGetStarted.iOS/EFGetStarted.iOS.csproj, samples/core/Xamarin/EFGetStarted.iOS/Main.cs
Xamarin.iOS requires the linker behavior to be set to `Don't Link`. Updating the sample to have the linker set to that value for all build configurations and updating the readme to note that as well.
=> Updating Xamarin sample with proper linker settings

entity-framework/core/providers/sqlite/limitations.md, entity-framework/toc.yml
=> Link to Microsoft.Data.Sqlite docs

entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/cli/powershell.md
These instructions will work on all supported versions.
Fixes #2285
=> Simplify tool installation instructions

.github/workflows/markdownlint.yml
Only triggers this job if Markdown files are touched, and not when the files under `entity-framework/ef6/` are changed
=> chore: Add paths filtering for markdownlint CI

samples/core/Querying/QueryFilters/Entities.cs
Can't say that this should actually be suppressed, but there was an existing suppression that wasn't working for the problem matcher in CI, and was showing warnings on each PR that touched the samples
=> chore: Disable CS0169 warning

entity-framework/core/modeling/generated-properties.md
Changed all instances of setup (noun) to the grammatically correct set up (verb).  Closes #2547
=> Correct "setup" noun to verb issue

.markdownlint.json, entity-framework/core/managing-schemas/migrations/index.md, entity-framework/core/managing-schemas/migrations/managing.md
Inline disabled in the case of old tab style headings
=> chore: Markdownlint cleanups

entity-framework/core/querying/index.md, entity-framework/core/querying/tracking.md
=> Clarify what happens in query when local changes/added entities

entity-framework/core/managing-schemas/migrations/index.md, entity-framework/core/managing-schemas/migrations/managing.md, entity-framework/core/managing-schemas/migrations/operations.md, entity-framework/core/miscellaneous/cli/dbcontext-creation.md, entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/cli/powershell.md, entity-framework/core/miscellaneous/connection-strings.md, entity-framework/core/modeling/entity-types.md, samples/core/Modeling/FluentAPI/TableExcludeFromMigrations.cs, samples/core/Schemas/Migrations/CustomOperation.cs, samples/core/Schemas/Migrations/CustomOperationMultiSql.cs, samples/core/Schemas/Migrations/CustomOperationSql.cs
Additional changes:
- Add tips about EXEC (fixes #2561)
- Add a tab for Get-Migration
- Update custom operation samples (fixes #1574)
- Fix some bad PMC examples (fixes #2296)
- Add examples using Name= (fixes #2145)
- Mention ExcludeFromMigrations (fixes #750)
- Rearrange connection strings page
- Use OutputDir instead of Namespace
Fixes #1050
=> Document passing design-time args

entity-framework/index.yml, entity-framework/toc.yml
=> Add EF Core survey as card and TOC item

entity-framework/core/providers/cosmos/limitations.md
=> Update Cosmos cross-partition limitation

entity-framework/core/modeling/shadow-properties.md, samples/core/Modeling/FluentAPI/IndexerProperty.cs
=> Add doc for indexer property

entity-framework/core/dbcontext-configuration/index.md, samples/core/Miscellaneous/ConfiguringDbContext/AdditionalConfiguration/ApplicationDbContext.cs, samples/core/Miscellaneous/ConfiguringDbContext/AdditionalProviderConfiguration/ApplicationDbContext.cs, samples/core/Miscellaneous/ConfiguringDbContext/ConfiguringDbContext.csproj, samples/core/Miscellaneous/ConfiguringDbContext/InheritDbContext/ApplicationDbContext.cs, samples/core/Miscellaneous/ConfiguringDbContext/WebApp/ApplicationDbContext.cs, samples/core/Miscellaneous/ConfiguringDbContext/WebApp/Controllers/MyController.cs, samples/core/Miscellaneous/ConfiguringDbContext/WebApp/Program.cs, samples/core/Miscellaneous/ConfiguringDbContext/WebApp/Startup.cs, samples/core/Miscellaneous/ConfiguringDbContext/WebApp/UseNewForWebApp.cs, samples/core/Miscellaneous/ConfiguringDbContext/WebApp/appsettings.Development.json, samples/core/Miscellaneous/ConfiguringDbContext/WebApp/appsettings.json, samples/core/Miscellaneous/ConfiguringDbContext/WithContextFactory/FactoryServicesExample.cs, samples/core/Miscellaneous/ConfiguringDbContext/WithContextFactory/MyController.cs, samples/core/Miscellaneous/ConfiguringDbContext/WithNew/ApplicationDbContext.cs, samples/core/Miscellaneous/ConfiguringDbContext/WithNewAndArgs/ApplicationDbContext.cs, samples/core/Miscellaneous/Testing/ItemsWebApi/ItemsWebApi/ItemsContext.cs, samples/core/Samples.sln
Draft
Fixes #594
Part of #876
Fixes #1390
Fixes #1923
Fixes #2241
Part of #2523
Part of #2549
Part of #1832
Let's discuss where this page should go and what goes underneath it. We had previously decided to keep this in Miscellaneous, but I now believe this would be better as a top-level item with the following subsections to go into more detail:
- DbContext lifetime, configuration and initialization
- Overview
- Connection strings
- Using dependency injection
- Connection resiliency
- Context pooling
=> New docs for context creation and initialization

entity-framework/core/saving/transactions.md
See https://github.com/dotnet/efcore/issues/23269
=> Add warning about savepoints not working on SQL Server with MARS

entity-framework/core/querying/related-data/eager.md, samples/core/Querying/RelatedData/Program.cs
Added example for using single Include/ThenInclude method call to load multiple navigations.
Fixes #2873
=> Fix to #2873 - ThenInclude required?

entity-framework/ef6/fundamentals/async.md, entity-framework/ef6/fundamentals/proxies.md
When identifiers are not formatted as code it causes issues with localization (https://github.com/MicrosoftDocs/feedback/issues/2083)
=> Format identifiers as code

entity-framework/core/extensions/index.md
=> Added extension EntityFrameworkCore.Triggered

.github/workflows/build-samples.yml, .github/workflows/markdownlint.yml
Removes CI warning on ubuntu-latest
=> Run Github Actions on Ubuntu 20.04

entity-framework/core/modeling/entity-properties.md, entity-framework/core/modeling/entity-types.md, samples/core/Modeling/DataAnnotations/ColumnComment.cs, samples/core/Modeling/DataAnnotations/TableComment.cs, samples/core/Modeling/FluentAPI/ColumnComment.cs, samples/core/Modeling/FluentAPI/TableComment.cs
=> Document comments

entity-framework/core/modeling/entity-types.md, entity-framework/core/querying/user-defined-function-mapping.md, entity-framework/index.yml, entity-framework/toc.yml, samples/core/Modeling/Conventions/Conventions.csproj, samples/core/Modeling/Conventions/EntityTypes.cs, samples/core/Modeling/Conventions/Program.cs, samples/core/Querying/UserDefinedFunctionMapping/Model.cs, samples/core/Querying/UserDefinedFunctionMapping/Program.cs, samples/core/Querying/UserDefinedFunctionMapping/UserDefinedFunctionMapping.csproj, samples/core/Samples.sln
=> Adding documentation for custom function mapping

entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
Fixes #2890
Fixes #2936
Fixes #2877
=> Add more model building breaking changes.

entity-framework/core/extensions/index.md, entity-framework/core/modeling/relationships.md, samples/core/Modeling/FluentAPI/Relationships/ManyToManyShared.cs
=> Add more M2M configuration samples

entity-framework/core/providers/cosmos/limitations.md
=> Add lack of support for collections of primitive types as a limitation

entity-framework/core/logging-events-diagnostics/events.md, entity-framework/core/logging-events-diagnostics/index.md, entity-framework/core/logging-events-diagnostics/interceptors.md, entity-framework/core/logging-events-diagnostics/simple-logging.md, entity-framework/core/modeling/inheritance.md, entity-framework/core/modeling/relationships.md, entity-framework/core/providers/cosmos/index.md, entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md
=> Reference 5.0 API using xref

entity-framework/core/modeling/value-comparers.md, samples/core/Modeling/ValueConversions/MappingImmutableClassProperty.cs, samples/core/Modeling/ValueConversions/MappingListPropertyOld.cs, samples/core/Modeling/ValueConversions/Program.cs, samples/core/Modeling/ValueConversions/ValueConversions.csproj
This started out as documentation for the new comparer fluent API, and then I got sucked into general improvements... :grin:
=> Improvements to value comparer docs

.markdownlint.json, .vscode/settings.json, entity-framework/core/modeling/owned-entities.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md, entity-framework/toc.yml
This rearranges features in the "what's new" page to no longer be grouped by preview, and links to up-to-date docs which have been added since. Major/significant features have their own sections (though reduced compared to before), all other features are listed as one-liners under "other features".
I've exercised some subjective judgement in selecting which features to classify as major and which not to, hope nobody gets hurt :rofl: Obviously this is a draft and feedback is welcome :)
=> Rearrange the 5.0 what's new page

entity-framework/core/extensions/index.md
=> Add more extensions

entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
=> Add .NET Standard 2.1 support to breaking changes

entity-framework/core/saving/cascade-delete.md, samples/core/CascadeDeletes/CascadeDeletes.csproj, samples/core/CascadeDeletes/IntroOptionalSamples.cs, samples/core/CascadeDeletes/IntroRequiredSamples.cs, samples/core/CascadeDeletes/OptionalDependentsSamples.cs, samples/core/CascadeDeletes/Program.cs, samples/core/CascadeDeletes/RequiredDependentsSamples.cs, samples/core/CascadeDeletes/WithDatabaseCycleSamples.cs, samples/core/Samples.sln
Fixes #473
Fixes #828
Fixes #998
Fixes #1926
Fixes #2367
Fixes #2426
Fixes #2906
=> Re-write cascade delete documentation

entity-framework/core/change-tracking/identity-resolution.md, entity-framework/core/modeling/keys.md, entity-framework/core/modeling/relationships.md, entity-framework/core/providers/writing-a-provider.md, entity-framework/core/testing/testing-sample.md
=> Change setup to set up

entity-framework/core/cli/dotnet.md, entity-framework/core/cli/powershell.md, entity-framework/core/managing-schemas/scaffolding.md, entity-framework/core/miscellaneous/connection-strings.md
Fixes #2805
Fixes #2995
I think I figured out the continual confusion here. The colon is always correct when reading from ASP.NET config JSON. However, when using UserSecrets, the secret can be stored as either `ConnectionString.Foo` or `ConnectionString:Foo`. We showed examples using periods, which then works when looking up with periods. But then this doesn't work for connection strings from configuration, even though the document makes the assumption that these things work the same.
The fix here is to use colons consistently. I also plan to update more of the connection strings documentation at a later time. But many people have hit this, so wanted to fix it now.
=> Use colons consistently for connection strings in UserSecrets

entity-framework/core/saving/cascade-delete.md
Missed because MD033 is turned off
=> fix: Unescaped HTML-like element in table

entity-framework/core/querying/tracking.md
The definite (the) and indefinite (a) articles are sometimes missing.
It is inconsistent so does not appear to be a conscious writing style.
I propose to add them, where missing, to improve comprehension.
=> fix grammar: add definite/ indefinite articles

entity-framework/core/modeling/relationships.md
Fixes #2563
We already have this warning in the change-tracking docs. Adding it also to the model building docs.
=> Document that implicitly chosen type for join table may change

entity-framework/core/modeling/value-comparers.md, entity-framework/core/modeling/value-conversions.md, samples/core/Modeling/ValueConversions/CaseInsensitiveStrings.cs, samples/core/Modeling/ValueConversions/CompositeValueObject.cs, samples/core/Modeling/ValueConversions/EncryptPropertyValues.cs, samples/core/Modeling/ValueConversions/EnumToStringConversions.cs, samples/core/Modeling/ValueConversions/FixedLengthStrings.cs, samples/core/Modeling/ValueConversions/KeyValueObjects.cs, samples/core/Modeling/ValueConversions/PreserveDateTimeKind.cs, samples/core/Modeling/ValueConversions/PrimitiveCollection.cs, samples/core/Modeling/ValueConversions/Program.cs, samples/core/Modeling/ValueConversions/SimpleValueObject.cs, samples/core/Modeling/ValueConversions/ULongConcurrency.cs, samples/core/Modeling/ValueConversions/ValueConversions.csproj, samples/core/Modeling/ValueConversions/ValueObjectCollection.cs, samples/core/Modeling/ValueConversions/WithMappingHints.cs
Lots of examples!
Fixes #614
Fixes #784
Part of #685
Fixes #2252
Fixes #2415
Fixes #2456
Fixes #2824
Fixes #2979
=> Updates to value converter docs

entity-framework/core/miscellaneous/collations-and-case-sensitivity.md, entity-framework/core/miscellaneous/nullable-reference-types.md, entity-framework/core/modeling/entity-properties.md, entity-framework/core/modeling/generated-properties.md, samples/core/Miscellaneous/Collations/Program.cs, samples/core/Miscellaneous/NullableReferenceTypes/Program.cs
=> Fix line ranges/regions

entity-framework/core/change-tracking/explicit-tracking.md, entity-framework/core/change-tracking/miscellaneous.md, entity-framework/core/cli/dotnet.md, entity-framework/ef6/fundamentals/configuring/code-based.md, samples/core/ChangeTracking/AdditionalChangeTrackingFeatures/Program.cs, samples/core/ChangeTracking/AdditionalChangeTrackingFeatures/Samples.cs
Fixes #3066
Fixes #3073
Fixes #3074
=> Localization fixes

entity-framework/core/what-is-new/nuget-packages.md, entity-framework/toc.yml
=> Add NuGet packages page

entity-framework/core/extensions/index.md
Added [EntityFramework.Exceptions](https://github.com/Giorgi/EntityFramework.Exceptions)
=> Added EntityFramework.Exceptions

entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
The "Breaking changes in EF Core 5.0" was stating otherwise and was updated.
=> .NET Core 2.1 does not support .NET Standard 2.1

samples/core/Saving/CascadeDelete/Sample.cs, samples/core/Saving/Disconnected/Sample.cs, samples/core/Saving/RelatedData/Sample.cs
=> Remove unnecessary AsQueryables

entity-framework/core/providers/sqlite/spatial.md
In the "Configuring SRID" section of the SQLite Spatial documentation there is an example that uses the "ForSqliteHasSrid()" method. According to the [.NET API Browser](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.sqlitepropertybuilderextensions.forsqlitehassrid?view=efcore-3.1) this method is obsolete and has been replaced with the "HasSrid()" method in EF Core 5.0. This change replaces the references to the obsolete method with references to the current method.
=> ForSqliteHasSrid() method is Obsolete

entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md
Fix a typo for the name of the SQL DATALENGTH function, changing from DATELENGTH
=> Update whatsnew.md to fix typo for SQL DATALENGTH function name

entity-framework/core/modeling/keyless-entity-types.md
I think the sentence "`ToView` assumes that the object already exists in the database and it won't be created by migrations." is old / misleading.
=> Update keyless-entity-types.md: Note about ToView()

entity-framework/core/extensions/index.md
[EntityFrameworkCore.Projectables](https://github.com/koenbeuk/EntityFrameworkCore.Projectables) enables a way to use normal properties and methods within your linq query while having it still generate proper sql. Similar to Expressionify, it uses a code generator to create companion expressions of any property/method that is marked with an attribute. I've been using this technique for a while now and have recently published this library as a generic implementation. It has quite a few differences from Expressionify as it first allows Expanding on much more than just extension methods as well as it integrates with EFCore and actually improves performance for query compilation (currently exposed in the Benchmark but I'll add a blog post on this topic soon too).
It would be great if this can …
=> Added an extensions entry for EntityFrameworkCore.Projectables

samples/core/GetStarted/Model.cs, samples/core/GetStarted/Program.cs
Used local folder for consistency.
=> Create platform and permissions neutral path for blog

entity-framework/core/modeling/inheritance.md
From https://github.com/dotnet/efcore/issues/25210, suggestion to add a note in the section on shared columns that some providers do not filter results by discriminator when casting a base entity to a child entity.
ping @AndriySvyryd
=> Add a note on querying shared columns

entity-framework/core/dbcontext-configuration/index.md
Remove trailing double quotes from `Use*` occurrences
=> Fix typo in dbcontext-configuration/index.md

entity-framework/core/managing-schemas/migrations/managing.md
Remove the duplicate mention of using EF Core tools when the `DbContext` is in a different assembly.
The same note is already at the beginning of the page
=> Remove duplicate note

entity-framework/ef6/fundamentals/databinding/wpf.md
I fixed a word based on the context (`you` > `your`) and added a dot (`.`) at the end of a paragraph.
=> Fix small type errors

entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md
Hi, 
I believe that the link to "Property Bags" can be improved by an anchor to the "Property bag entity types" section. 
If I'm wrong, please reject this pull request.
=> Improve link to Property Bags documentation page for What's New in EF Core 5.0 page

entity-framework/core/what-is-new/ef-core-6.0/breaking-changes.md
For https://github.com/dotnet/efcore/issues/19828
=> Breaking change note for removal of the last ordering 

entity-framework/core/modeling/indexes.md, entity-framework/core/performance/efficient-querying.md, entity-framework/toc.yml, samples/core/Modeling/IndexesAndConstraints/DataAnnotations/Index.cs, samples/core/Modeling/IndexesAndConstraints/DataAnnotations/IndexComposite.cs, samples/core/Modeling/IndexesAndConstraints/DataAnnotations/IndexName.cs, samples/core/Modeling/IndexesAndConstraints/DataAnnotations/IndexUnique.cs, samples/core/Modeling/IndexesAndConstraints/FluentAPI/CheckConstraint.cs, samples/core/Modeling/IndexesAndConstraints/FluentAPI/Index.cs, samples/core/Modeling/IndexesAndConstraints/FluentAPI/IndexComposite.cs, samples/core/Modeling/IndexesAndConstraints/FluentAPI/IndexFilter.cs, samples/core/Modeling/IndexesAndConstraints/FluentAPI/IndexInclude.cs, samples/core/Modeling/IndexesAndConstraints/FluentAPI/IndexName.cs, samples/core/Modeling/IndexesAndConstraints/FluentAPI/IndexNoFilter.cs, samples/core/Modeling/IndexesAndConstraints/FluentAPI/IndexUnique.cs, samples/core/Modeling/IndexesAndConstraints/IndexesAndConstraints.csproj, samples/core/Modeling/IndexesAndConstraints/Program.cs, samples/core/Samples.sln
Also move index/constraint docs to their own project, instead of putting everything into FluentAPI/DataAnnotations projects.
Closes #3063
=> Document check constraints

entity-framework/core/miscellaneous/async.md, entity-framework/core/what-is-new/ef-core-6.0/breaking-changes.md
=> Breaking change note on DbSet not implement IAsyncEnumerable

entity-framework/core/providers/sql-server/functions.md
Closes #3462
We could document that the translation changed across versions, but I honestly don't think it's worth it.
=> Update translation for SQL Server string.IsNullOrWhitespace

entity-framework/core/what-is-new/ef-core-6.0/breaking-changes.md
=> Document extensions breaking changes

entity-framework/core/extensions/index.md
=> Add NuGet links

entity-framework/core/cli/dotnet.md, entity-framework/core/cli/powershell.md, entity-framework/core/managing-schemas/migrations/applying.md
=> Document Migration Bundles

entity-framework/core/what-is-new/ef-core-6.0/whatsnew.md, samples/core/Miscellaneous/NewInEFCore6/HasConversionSample.cs, samples/core/Miscellaneous/NewInEFCore6/PreConventionModelConfigurationSample.cs, samples/core/Modeling/ValueConversions/CompositeValueObject.cs, samples/core/Modeling/ValueConversions/ValueObjectCollection.cs
=> Correct Stirling -> Sterling

entity-framework/core/what-is-new/ef-core-6.0/whatsnew.md
Constraints on PostTag where referencing wrong tables based on name
Posts table also included a reference to Blog table not listed in example
=> Correct SQL in many-to-many scaffold sample

entity-framework/core/change-tracking/miscellaneous.md, entity-framework/core/cli/dotnet.md, entity-framework/core/cli/powershell.md, entity-framework/core/logging-events-diagnostics/index.md, entity-framework/core/logging-events-diagnostics/interceptors.md, entity-framework/core/miscellaneous/platforms.md, entity-framework/core/modeling/backing-field.md, entity-framework/core/modeling/keyless-entity-types.md, entity-framework/core/modeling/relationships.md, entity-framework/core/modeling/spatial.md, entity-framework/core/modeling/table-splitting.md, entity-framework/core/modeling/value-comparers.md, entity-framework/core/providers/cosmos/index.md, entity-framework/core/providers/sql-server/functions.md, entity-framework/core/providers/sql-server/index.md, entity-framework/core/providers/sql-server/value-generation.md, entity-framework/core/providers/sqlite/functions.md, entity-framework/core/providers/sqlite/limitations.md, entity-framework/core/querying/raw-sql.md, entity-framework/core/querying/tracking.md, entity-framework/toc.yml
I took a pretty extreme approach of removing all irrelevant information about unsupported versions from the main docs. Mostly because I hope that everyone has already upgraded to a supported version and isn't still actively developing on these older versions.
Please push back on any information that you still think is still relevant to readers.
=> End of life 2.1

entity-framework/core/extensions/index.md
I am in no way related with the framework nor its author.
This has been just a quick find; I would certainly like someone to evaluate it in more detail. I do not have the time budget to assess it and we could discuss whatever I have the means in the first place.
The repository contains a .dll which is provided to [LoadExtension](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlite.sqliteconnection.loadextension?view=msdata-sqlite-6.0.0) for testing. As much as I understand what it _might_ be, it made me raise an eyebrow as I don't enjoy having binaries into repositories.
I am also unable to assess whatever conversion of method calls is reasonably complete.
Nonetheless, I think the API is good, and the library has value.
=> Mentioning Laraue.EfCoreTriggers

entity-framework/core/saving/disconnected-entities.md
It looks like this was meant to read "implemented **by** using query filters" or simply "implemented using query filters". I opted to fix it to the latter.
=> Fix typo in disconnected-entities.md

samples/core/GetStarted/Model.cs
This makes the code shorter and easier to understand.
=> Simplify code

entity-framework/core/logging-events-diagnostics/event-counters.md
Added counter labels for all counters, and added a reference to the EventSource file where the counters are maintained.
The table ends up being rather "ugly" with the long counter names, so I force a line break in the counter name cell. Not sure this is the right approach for controlling the style, let me know if you want if changed.
This should solve #3234
=> Added labels and reference to the counters file

entity-framework/core/cli/powershell.md, entity-framework/core/modeling/bulk-configuration.md, entity-framework/core/providers/cosmos/unstructured-data.md, entity-framework/toc.yml, samples/core/Modeling/BulkConfiguration/BulkConfiguration.csproj, samples/core/Modeling/BulkConfiguration/Currency.cs, samples/core/Modeling/BulkConfiguration/CurrencyConverter.cs, samples/core/Modeling/BulkConfiguration/MetadataAPIContext.cs, samples/core/Modeling/BulkConfiguration/PreConventionContext.cs, samples/core/Modeling/BulkConfiguration/Product.cs, samples/core/Modeling/BulkConfiguration/Program.cs, samples/core/Samples.sln
=> Add documentation for pre-convention model configuration 

entity-framework/core/what-is-new/ef-core-6.0/breaking-changes.md
Links which did not use xref were broken (lines 136 and 159). Line 103 worked but I wanted to unify it with the rest. There are two options:
1. use xref - longer path, doesnt require .md suffix
2. use just file name - required .md suffix to work in github
I went with option n.2. Not adding the .md suffix would probably work on docs.microsoft.com website but doesn't work when browsing on github.
=> Fix links from Breaking changes to What's new

entity-framework/core/miscellaneous/platforms.md
=> Update platforms page for 6.0

entity-framework/core/what-is-new/ef-core-7.0/plan.md
=> fix typo in 7.0 plan.md

entity-framework/ef6/modeling/code-first/migrations/teams.md
Changing "thru" -> "through" in "Code First Migrations in Team Environments".
=> Fix minor typo: code-first/migrations/team.md

entity-framework/core/performance/efficient-querying.md, entity-framework/core/querying/pagination.md, entity-framework/toc.yml, samples/core/Querying/Pagination/BloggingContext.cs, samples/core/Querying/Pagination/Pagination.csproj, samples/core/Querying/Pagination/Program.cs, samples/core/Samples.sln
Note: this is a section under "efficient querying" under performance. But it could also be its own page under the top-level "Query data", since this isn't only about performance, but also about general correctness.
Closes #3582
=> Document good pagination practices

entity-framework/core/querying/tracking.md, samples/core/Querying/Tracking/NonTrackingBloggingContext.cs
=> Document UseQueryTrackingBehavior

entity-framework/toc.yml
DbContext Pooling used to be a page under Miscellaneous, but was moved to the Advanced Performance Topics page under Performance. A redirection is already in place, but the old TOC entry was left in place.
=> Remove DbContext Pooling from Miscellaneous TOC

entity-framework/core/what-is-new/ef-core-6.0/breaking-changes.md
=> Document IExecutionStrategy lifetime breaking change

entity-framework/core/providers/cosmos/index.md, entity-framework/toc.yml, samples/core/Miscellaneous/NewInEFCore6.Cosmos/CosmosModelConfigurationSample.cs
Document basic support for collections of primitive types in Cosmos
Fixes #3597
Fixes #3358
=> Document Cosmos throughput configuration

entity-framework/efcore-and-ef6/porting/index.md, entity-framework/efcore-and-ef6/porting/port-behavior.md, entity-framework/efcore-and-ef6/porting/port-code.md, entity-framework/efcore-and-ef6/porting/port-database.md, entity-framework/efcore-and-ef6/porting/port-detailed-cases.md, entity-framework/efcore-and-ef6/porting/port-edmx.md, entity-framework/efcore-and-ef6/porting/port-hybrid.md
Includes conversion from relative path to xref: for better validation.
=> Fix broken links in porting guide

entity-framework/core/providers/writing-a-provider.md
=> Some provider writer instructions on SQL baselines

entity-framework/core/performance/advanced-performance-topics.md
=> Fixes grammatical error in EF Core Advanced Performance Topics Doc, under Compiled queries

entity-framework/core/modeling/index.md, samples/core/Modeling/EntityProperties/DataAnnotations/Annotations.cs, samples/core/Modeling/EntityProperties/DataAnnotations/Required.cs
This is the first and only place in the hand-out where `using` declarations are explicitly given.
`[Table]` attribute is used later on, so I added the namespace for it here.
I also added the `[Table]` attribute, otherwise the namespace would be unneeded for the given snippet.
=> using System.ComponentModel.DataAnnotations.Schema

entity-framework/core/testing/testing-with-the-database.md, entity-framework/core/testing/testing-without-the-database.md
Fix a handful of minor typos in _Testing against your production database system_.
I also noticed while reading the document that the two blog controller code samples are empty, ~and the link to that code 404s~ (fixed in commit 2), but I don't know what they _should_ be to fix that.
=> Fix a few typos

entity-framework/core/querying/pagination.md, entity-framework/core/querying/single-split-queries.md
In split query, and also a stronger note in the pagination page.
Closes #3242
=> Warnings for deterministic ordering

entity-framework/core/testing/testing-with-the-database.md, samples/core/Testing/BloggingWebApi/Controllers/BloggingController.cs
=> Fix testing sample links

entity-framework/core/modeling/entity-types.md, entity-framework/core/modeling/keyless-entity-types.md, entity-framework/core/testing/testing-without-the-database.md, samples/core/Testing/BusinessLogic/BloggingContext.cs, samples/core/Testing/BusinessLogic/BusinessLogic.csproj, samples/core/Testing/BusinessLogic/UrlResource.cs, samples/core/Testing/TestingWithoutTheDatabase/InMemoryBloggingControllerTest.cs, samples/core/Testing/TestingWithoutTheDatabase/SqliteInMemoryBloggingControllerTest.cs, samples/core/Testing/TestingWithoutTheDatabase/TestingWithoutTheDatabase.csproj
=> Document ToInMemoryQuery and re-introduce sample code

samples/core/Performance/Other/BloggingContext.cs
Fixes Simple logging region for https://github.com/dotnet/EntityFramework.Docs/edit/main/entity-framework/core/performance/performance-diagnosis.md
(https://docs.microsoft.com/en-us/ef/core/performance/performance-diagnosis?tabs=simple-logging%2Ccalculate-in-database)
=> Fix missing Simple Logging region

entity-framework/core/miscellaneous/nullable-reference-types.md, entity-framework/core/modeling/entity-properties.md
=> Update comments on NRT being on/off by default

entity-framework/core/performance/efficient-querying.md
This is the one and only occurrence of the MARS abbreviation, so it should include the full form.
=> Add What MARS abbreviation stands for

entity-framework/core/performance/advanced-performance-topics.md, samples/core/Performance/AspNetContextPoolingWithState/ITenant.cs, samples/core/Performance/AspNetContextPoolingWithState/Program.cs, samples/core/Performance/AspNetContextPoolingWithState/Tenant.cs, samples/core/Performance/AspNetContextPoolingWithState/WeatherForecastScopedFactory.cs
To have a proper, scoped ITenant service.
Closes #3787
=> Update docs for DbContext pooling with state

entity-framework/core/miscellaneous/multitenancy.md
For better visibility & understanding before someone undertakes the steps.
Minor change. Based on a tweet I saw where someone suggested the change. Figured I'd just do a PR. :)
=> Move warning to the top of the section

samples/core/GetStarted/Model.cs, samples/core/GetStarted/Program.cs
Migrate EFGetStarted sample to using top-level statements feature. (https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements)
=> Top-level statements for EFGetStarted

entity-framework/core/managing-schemas/migrations/index.md, entity-framework/core/miscellaneous/collations-and-case-sensitivity.md, entity-framework/core/modeling/relationships.md, entity-framework/core/modeling/spatial.md, entity-framework/core/querying/pagination.md
And rename EF Community Standup -> .NET Data Community Standup
=> Add pagination resource links

entity-framework/core/providers/sql-server/misc.md, entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md, entity-framework/toc.yml, samples/core/SqlServer/Misc/Blog.cs, samples/core/SqlServer/Misc/TriggersContext.cs, samples/core/SqlServer/SqlServer.csproj
=> Document SQL Server + triggers breaking change

entity-framework/core/miscellaneous/connection-resiliency.md
There was a small mismatch between the thrown exception message and the mentioned exception message. This leads to no results on searches by exact phrasing.
=> Fix InvalidOperationException

entity-framework/core/testing/testing-with-the-database.md
Looks like some verb like `have` was missing.
=> Fix missing word in Testing with db

entity-framework/core/managing-schemas/scaffolding/index.md, entity-framework/core/managing-schemas/scaffolding/templates.md, entity-framework/core/what-is-new/ef-core-7.0/whatsnew.md, entity-framework/index.yml, entity-framework/toc.yml
=> What's new in EF7: Custom RevEng Templates

entity-framework/ef6/fundamentals/testing/mocking.md
Currently the underlying data collection's `GetEnumerator()` is only invoked once, and the resulting value is used every time the mocked `DbSet`'s `GetEnumerator()` method is invoked. The mocked `DbSet` needs to be configured to retrieve a new enumerator each time the method is called by invoking the underlying data collection's `GetEnumerator()` method. Otherwise the enumerator returned by the method will become invalid if the contents of the mocked `DbSet` change. 
Since the example sets up the underlying data before configuring the mock, and doesn't make any subsiquent changes after that point, this doesn't cause any issues in the example. But if the same setup code is used in a unit test that involves modifying the contents of the DbSet, the code will throw …
=> Fixed GetEnumerator() method on mock

entity-framework/core/providers/cosmos/functions.md, entity-framework/core/providers/sql-server/functions.md, entity-framework/core/providers/sql-server/spatial.md, entity-framework/core/providers/sqlite/functions.md, entity-framework/core/providers/sqlite/spatial.md, entity-framework/core/querying/complex-query-operators.md
=> Add EF7 function translations

CONTRIBUTING.md, README.md, entity-framework/core/providers/cosmos/planetary-docs-sample.md, entity-framework/dotnet-data/index.yml, entity-framework/ef6/fundamentals/performance/perf-whitepaper.md, samples/end2end/PlanetaryDocs/README.md
**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck
=> [BULK] DocuTune - Fix build validation issues: docs-link-absolute

entity-framework/core/testing/choosing-a-testing-strategy.md
=> Fix typo in testing/choosing-a-testing-strategy.md

entity-framework/docfx.json
Hello, this content needs to use the Microsoft 365 product-level header. Please let me know if you have any questions. If you're wondering "What is a product-level header?" please see:  https://review.docs.microsoft.com/en-us/help/onboard/admin/navigation-product-level-header?branch=main#what-is-product-level-navigation-for
=> Added .NET product header metadata

samples/core/Miscellaneous/NewInEFCore7/DocumentsContext.cs, samples/core/Miscellaneous/NewInEFCore7/DocumentsContextStoredProcedures.cs, samples/core/Miscellaneous/NewInEFCore7/ExecuteDeleteSample.cs, samples/core/Miscellaneous/NewInEFCore7/ExecuteUpdateSample.cs, samples/core/Miscellaneous/NewInEFCore7/JsonColumnsSample.cs, samples/core/Miscellaneous/NewInEFCore7/ModelBuildingConventionsSample.cs, samples/core/Miscellaneous/NewInEFCore7/NewInEFCore7.csproj, samples/core/Miscellaneous/NewInEFCore7/Program.cs, samples/core/Miscellaneous/NewInEFCore7/StoredProcedureMappingSample.cs, samples/core/Miscellaneous/NewInEFCore7/TpcInheritanceSample.cs
=> Sample for stored procedure mapping

entity-framework/core/providers/sql-server/columns.md
=> Document the new support for SQL Server UTF-8 columns

CONTRIBUTING.md, README.md, entity-framework/dotnet-data/index.yml, entity-framework/ef6/fundamentals/performance/perf-whitepaper.md, entity-framework/index.yml, samples/end2end/PlanetaryDocs/README.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
**DO NOT MERGE THIS PULL REQUEST WHILE IN DRAFT STATUS!** Some of the changes to links and other content are not valid until after go-live.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: …
=> [BULK UPDATE] DocuTune - Rebranding links

entity-framework/core/modeling/backing-field.md
The documentation was missing the convention for a non prefixed camel case backing field.
Issue - https://github.com/dotnet/EntityFramework.Docs/issues/4061
=> Backing field camel case fix

entity-framework/core/what-is-new/index.md
Also update supported dates to match latest dates on the .NET releases page.
=> Add EF7 to releases page

entity-framework/core/providers/sql-server/misc.md, entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md
=> Document 7.0 SaveChanges incompatibility with some computed columns

entity-framework/core/modeling/value-conversions.md
=> Update value conversion docs for EF 7.0

entity-framework/core/testing/index.md
This small PR removes a stray "a" from the sentence "it's highly recommended to plan for a testing early...." since it is unnecessary and grammatically incorrect.
=> Fix minor grammatical error in index.md

entity-framework/core/modeling/keys.md
Value generation and other page content are being rendered inside the tabbed code sample.
See below:
=> Fix page content being part of tabbed content

entity-framework/core/providers/sql-server/misc.md, entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md
=> Clarify the trigger convention's usage in the breaking change note

entity-framework/core/extensions/index.md
Added Entity Framework Ruler to the bottom of the Extensions section
=> Added extension reference for Entity Framework Ruler

entity-framework/core/extensions/index.md
Add the introduction to LessCode.EFCore.StronglyTypedId
As proposed on [https://github.com/dotnet/EntityFramework.Docs/issues/4160#issuecomment-1327216363](https://github.com/dotnet/EntityFramework.Docs/issues/4160#issuecomment-1327216363)
=> Add the introduction to LessCode.EFCore.StronglyTypedId

entity-framework/core/miscellaneous/async.md, entity-framework/core/performance/efficient-querying.md, entity-framework/core/providers/sql-server/index.md
=> Add note on SqlClient async issues in perf docs

entity-framework/core/querying/single-split-queries.md
Introduce the distinction between cartesian explosion and the (less important) data duplication, and provide examples.
See https://github.com/dotnet/efcore/issues/29665 for a discussion around this.
=> Improve description of single/split queries

entity-framework/core/what-is-new/release-planning.md
We could also leave the section, saying that we don't do these, but it seems kinda useless.
=> Remove "minor releases" from the release planning page

entity-framework/core/querying/single-split-queries.md
Hi team,
This is my first contribution to such a big project. I hope that these changes will clarify and supplement the article.
1. Propose to rename variables from one letter style to the whole word. 'blog' and 'post' are not as long as they could be. By the way, another sections contain the whole word naming.
2. The main change is in the ThenInclude method. For some people, the letter "b" here can be confusing, so this modification should clarify that Comments is a collection navigation of Post type, not of Blog type.
Thank you in advance 😃
=> Rename identifier in ThenInclude method (Cartesian explosion section)

entity-framework/core/querying/related-data/eager.md
Previous wording made it sound like only the second example was the correct way to do things.
=> Clarify that both filtered include examples are valid

entity-framework/core/what-is-new/ef-core-8.0/breaking-changes.md
=> Breaking change note for DateOnly/TimeOnly scaffolding

entity-framework/core/dbcontext-configuration/index.md, entity-framework/core/providers/in-memory/index.md, entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md, entity-framework/toc.yml
=> Update guidance around in-memory database

entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md
=> Document SQLite breaking change around the RETURNING clause

entity-framework/core/extensions/index.md
Updating supported EF Core versions for `Ainoraz.EFCore.IncludeBuilder`.
=> Ainoraz.EFCore.IncludeBuilder supports EF7

entity-framework/core/managing-schemas/migrations/managing.md
=> Improve instructions on resetting migrations

entity-framework/core/modeling/index.md
=> Document EntityTypeConfigurationAttribute

entity-framework/core/modeling/relationships.md
This eliminates an occurrence of a duplicated "of" and a duplicated "the".
=> Fix a couple of typos in the relationships docs

entity-framework/core/modeling/relationships/many-to-many.md, entity-framework/core/modeling/relationships/mapping-attributes.md, entity-framework/core/modeling/relationships/one-to-many.md, entity-framework/core/modeling/relationships/one-to-one.md
Just like #4309, this one too contains trivial fixes to tiny typos.
=> Touch-ups to the "relationships" documentation

entity-framework/core/testing/testing-without-the-database.md
=> Include closing brace in partial repository code

samples/core/Modeling/Inheritance/FluentAPI/NonShadowDiscriminator.cs
The sample is missing a `HasValue` statement, which actually does the mapping. The `HasValue` statement is available for the sample with shadow mappings.
These docs will be changed by this PR: [Inheritance - Table per Hierarchy And Discriminator Configuration](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-hierarchy-and-discriminator-configuration)
This other sample using untyped mappings for the discriminator is using the `HasValue` statement correctly: [Sample with shadow mappings](https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Modeling/Inheritance/FluentAPI/DiscriminatorConfiguration.cs)
=> Complete the sample with the typed discriminator mapping

entity-framework/core/what-is-new/ef-core-8.0/whatsnew.md, samples/core/Miscellaneous/NewInEFCore8/JsonColumnsSample.cs, samples/core/Miscellaneous/NewInEFCore8/LazyLoadingSample.cs, samples/core/Miscellaneous/NewInEFCore8/NewInEFCore8.csproj, samples/core/Miscellaneous/NewInEFCore8/PrimitiveCollectionToTableSample.cs, samples/core/Miscellaneous/NewInEFCore8/PrimitiveCollectionsInJsonSample.cs, samples/core/Miscellaneous/NewInEFCore8/PrimitiveCollectionsSample.cs, samples/core/Miscellaneous/NewInEFCore8/Program.cs
=> What's new in EF8 Preview 4

entity-framework/core/miscellaneous/nullable-reference-types.md, samples/core/Miscellaneous/NullableReferenceTypes/Program.cs
=> Fix optional navigation sample in NRT page

samples/end2end/PlanetaryDocs/README.md
Since .NET Core is not the main technology focus for this sample, I removed it. Also, we're trying to retire the .NET Core label from the site experience.
Contributes to https://github.com/dotnet/docs/issues/35970
=> Remove dotnet-core metadata

entity-framework/core/modeling/value-conversions.md
Because of e.g. https://github.com/dotnet/efcore/issues/31172
=> Add note on value-converted properties not being queryable

entity-framework/core/providers/writing-a-provider.md
Integrate the [list](https://github.com/dotnet/EntityFramework.Docs/issues/1920#issuecomment-1646246258) graciously compiled by Brice into our provider writer "docs".
=> Integrate internal architecture videos in the "writing a provider" page

entity-framework/core/providers/cosmos/functions.md, entity-framework/core/providers/sql-server/functions.md, entity-framework/core/providers/sqlite/functions.md, entity-framework/core/what-is-new/ef-core-8.0/breaking-changes.md
Part of #4419
~~Blocked waiting for dotnet/efcore#31356~~
=> Add new SQLite Math function mappings

entity-framework/core/what-is-new/ef-core-8.0/whatsnew.md
- has-pending-model-changes (resolves #4481)
- SQLite RevEng improvements (resolves #4482)
Preview: https://review.learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew?branch=pr-en-us-4491#checking-for-pending-model-changes
=> More of what's new in 8

entity-framework/core/change-tracking/change-detection.md
The word `using` appeared twice, once normally and once in italic. I left the italic one
=> Fixed typo in change-detection.md

entity-framework/breadcrumb/toc.yml, entity-framework/docfx.json
This PR brings breadcrumb implementation into alignment with [platform architecture requirements](https://review.learn.microsoft.com/en-us/help/platform/navigation-overview?branch=main#requirements-for-content-ecosystems). This PR is part of a previously announced batch of breadcrumb fixes across the Learn platform and will be auto-merged if there are no build warnings. This PR may include removing the “extend breadcrumb” feature from any docfx files that are still using it, fixing breadcrumb file references in the docfx file, and rewriting breadcrumb files to match the [approved breadcrumb pattern](https://review.learn.microsoft.com/en-us/help/platform/navigation-breadcrumbs-overview?branch=main#breadcrumbs-in-documentation) for a given product’s documentation.
=> Fix breadcrumbs

entity-framework/core/extensions/index.md
My proposal is to add [efmig](https://github.com/stil/efmig) to Tools section. 
I've been using it for my daily professional and personal work for more than 2 years now.
I've covered the most popular use cases such as creation of migrations code or generation of scripts as well as support for rollbacking.
It also plays well when working with different dotnet-ef/.NET Runtime/EF Core versions as it uses local versions for everything.
The additional advantage is that it allows to drop dependency on `Microsoft.EntityFrameworkCore.Design` in the project itself, it also works well with multiple DbContexts in the single .csproj
I believe the community would like to try out alternatives to the dotnet-ef CLI interface.
=> Add efmig to Tools section

entity-framework/core/modeling/indexes.md
Note: support for multiple indexes was added in 5.0 (https://github.com/dotnet/efcore/issues/21089).
Fixes #4582
=> Document multiple index support

entity-framework/core/extensions/index.md
In this pull:
- I updated 3 libraries I own to specify they now support EF Core 8
- Fixed the NuGet link for Entity Framework Extensions (was the wrong link)
Question:
- Would you want me on a different pull to go over all libraries and update the version if they support EF Core 8? (By using the convention "EF Core: [minVersion]-[maxVersion]"?
=> Update EF Core version + Fixed link

entity-framework/core/extensions/index.md
In this pull:
- Updated all versions to use "For EF Core: [minVersion]-[maxVersion]" whenever there is more than 1 version
- NOTE: I didn't touch on version for 
- Updated all [maxVersion] that I could find if EF Core 8 is supported or not (Some other packages probably support it, but if there was not a clear dependency, I didn't touch them)
=> Update Extensions Version

samples/core/Modeling/Relationships/ManyToMany.cs
Replaced `new()` with .NET 8 new collection initialization syntax `[]`
Only in [ManyToMany.cs](https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Modeling/Relationships/ManyToMany.cs) which affects [Many-to-Many relationships docs](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many).
=> Replaced new() with []

entity-framework/core/managing-schemas/scaffolding/index.md
the collection is now initialised in the nav member as List<T> and not as HashSet<T> in the ctor
IMHO the ICollection<T> abstraction is also pointless as you lose out on specifics like Count property [having to invoke the expensive Count() method instead]. Yes I agree there is T4 sophistication for experts but novices should fall into the pit of success.
=> no more HashSet<T> in ctor

entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md
I think while preparing for EF Core 9, some typos (wrong version numbers for this doc, which details breaking changes from 6 to 7) were introduced. Also, the link for breaking changes from 6 to 7 should not be here, since that link points to this doc
=> Correct typo (version numbers and link) in breaking-changes.md

entity-framework/core/modeling/relationships/many-to-many.md
typical signature overloads have params (joinEntityName, configureRight, configureLeft, configureJoinEntityType) in that order, but all the docs invert the left / right delegate ordering.
This can give rise to join table with conflicting field names and FK navs, so is dangerous for learning "skip navigation".
As Arthur wrote earlier "**the code gets complicated quickly and its easy to make a mistake**", yup!
The Issue #4269  ' Major overhaul of the "relationships" documentation' needs correcting, so I offer this PR.
HTH.
=> fix l/r in many-to-many.md for UsingEntity method calls

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/a-general-issue.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/z-customer-feedback.yml, entity-framework/docfx.json
1. Create new YML based templates, removing the old markdown based template.
1. Add the issue-template config file.
1. Update docfx.json to match the new templates.
=> Enable new Open Source feedback control

entity-framework/toc.yml
in most of the toc EF Core is always referred to as EF Core X.Y for versioning, figure this will make it consistent
=> update versions to align

entity-framework/core/what-is-new/ef-core-8.0/breaking-changes.md
Fix forgotten closing parenthesis on EF Core 8 breaking changes page.
=> Fix closing parenthesis EFCore8 breaking changes

entity-framework/core/what-is-new/ef-core-6.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-8.0/breaking-changes.md
Fixes #4608
Part of #4538
Fixes #4315
Fixes #4257
Fixes #4655
Fixes #4654
=> Updates to breaking changes

entity-framework/core/miscellaneous/platforms.md
Small update to include EF Core 8.0 and mention it targets .NET 8.0
=> Update '.NET implementations supported by EF Core' page to include EF Core 8.0

entity-framework/core/what-is-new/ef-core-8.0/whatsnew.md
I've fixed a small grammatical error in the "Numeric rowversions for SQL Azure/SQL Server" section.
=> Fixed small grammatical error

entity-framework/core/extensions/index.md
The original link to the EF Core Power Tools CLI was broken. 
I have updated it with a link to the most recent (EF7) readme
=> Updated EF Core Power Tools CLI link

entity-framework/core/extensions/index.md
Reconciler is an extension that allows to update an entity graph to match a given one.
This was already once part of this page, but I asked to remove it several years ago as it was too buggy. I recently had a good overhaul and extended the test suite significantly. I think it's now ready to be listed again.
=> Add Reconciler to list of extensions

entity-framework/core/providers/index.md
Today, a student tried to copy paste the existing snippet, which resulted in the "Unrecognized escape sequence" error.
This PR updates the example to indicate that the connection string is to be interpreted verbatim.
This occurs on the page: https://learn.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli#adding-a-database-provider-to-your-application
=> fix "Unrecognized escape sequence" in snippet

entity-framework/core/performance/advanced-performance-topics.md
At the "Query caching and parameterization" section in the document the C# snippets evolves around "Post" entity while the SQL snippets evolves around "Blog" entity. 
This commit unifies these entities to "Post" entity.
=> Update advanced-performance-topics.md to match SQL and C# Queries

entity-framework/core/what-is-new/ef-core-9.0/breaking-changes.md
For https://github.com/dotnet/efcore/pull/33815.
=> Add documentation for breaking change.

entity-framework/core/logging-events-diagnostics/metrics.md
Can't put an H2 as the first piece of content. The text under H1 **is** the introduction and is used for SEO
=> Fix header violation

entity-framework/core/querying/sql-queries.md
There has been enough confusion on the need to quote `Values` when using SqlQuery (on PostgreSQL), that I think it makes sense to introduce per-provider tabs on that code sample.
Note: IIRC this is the first time we add a PG sample/call-out in our docs.
See https://github.com/npgsql/efcore.pg/issues/2739
=> Add different provider code samples for SqlQuery

entity-framework/core/providers/sql-server/functions.md, entity-framework/core/providers/sqlite/functions.md, entity-framework/core/what-is-new/ef-core-9.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-9.0/whatsnew.md, samples/core/Miscellaneous/NewInEFCore9/QuerySample.cs
also:
- Breaking change note for https://github.com/dotnet/efcore/issues/33942
- Update function mappings
Fixes #4765
Fixes #4805
=> Whats new in EF9 docs

entity-framework/core/querying/single-split-queries.md
It's a bit early to be talking about EF 10, before 9 is even out 😅 But it seems OK to me... If we think we shouldn't, we can have a 10 branch for stuff like this, which we'd merge at some point later (but not sure it's worth the bother, plus merge conflicts...).
See https://github.com/dotnet/efcore/issues/26808
=> Limit the split query determinism warning to EF version prior to 10

samples/core/Benchmarks/QueryTrackingBehavior.cs
Without modification this benchmark fails as blog url and post title and content are not marked as nullable ? and we don't explicitly insert into these fields in the SeedData method so SQL Server rejects the insert.
Have amended SeedData to insert dummy data into blog.url, and post.title and post.content. 
Alternative is to remove these fields or mark them as nullable but in the context of tracking v no-tracking, better to keep a more realistic scenario and just populate the fields IMHO.
=> Update QueryTrackingBehavior benchmark as it fails due to attempts to insert nulls into not nullable db columns

entity-framework/core/what-is-new/ef-core-8.0/breaking-changes.md, entity-framework/toc.yml
=> Add missed 8.0 breaking changes.

.markdownlint.json
=> Disable MD041 requirement of h1 at top of file

.markdownlint.json
Fix
Line 0: [Warning] H1 is required. Use a single hash (#) followed by a space to create your top-level heading.
=> Fix  H1 is required

entity-framework/docfx.json
After this merges I'll test and  revert #4856
Do the same test as #4859
=> Don't build includes

.markdownlint.json
Reverts dotnet/EntityFramework.Docs#4856
#4860 is the better way to fix the include problem
=> Revert "Fix  H1 is required"

entity-framework/core/miscellaneous/nativeaot-and-precompiled-queries.md, entity-framework/core/performance/nativeaot-and-precompiled-queries.md, entity-framework/core/what-is-new/ef-core-9.0/whatsnew.md, entity-framework/toc.yml
=> Documentation for NativeAOT/precompiled queries

entity-framework/core/providers/sql-server/functions.md
also reorder DateOnly static members to appear before instance members - in line with DateTime and DateTimeOffset
=> correct TimeOnly member names to not be plural

entity-framework/core/cli/dotnet.md, entity-framework/core/cli/msbuild.md, entity-framework/core/cli/powershell.md, entity-framework/core/dbcontext-configuration/index.md, entity-framework/core/managing-schemas/migrations/applying.md, entity-framework/core/managing-schemas/scaffolding/index.md, entity-framework/core/miscellaneous/connection-strings.md, entity-framework/core/performance/nativeaot-and-precompiled-queries.md, entity-framework/core/what-is-new/ef-core-9.0/whatsnew.md, entity-framework/core/what-is-new/nuget-packages.md, entity-framework/toc.yml, samples/core/Miscellaneous/ConfiguringDbContext/ConfiguringDbContext.csproj, samples/core/Miscellaneous/ConfiguringDbContext/WebApp/Program.cs, samples/core/Miscellaneous/ConfiguringDbContext/WebApp9/Program9.cs
Clean up connection string documentation
Fixes #4700
=> Add documentation for MSBuild integration

entity-framework/core/performance/nativeaot-and-precompiled-queries.md
=> Fix: net ef dbcontext --> dotnet ef dbcontext

entity-framework/core/what-is-new/index.md
=> Update what's new index page for EF 9

entity-framework/core/extensions/index.md
The current Bricelam.EntityFrameworkCore.Pluralizer and EntityFrameworkCore.ConfigurationManager binaries continue to work in EF9
=> Bump some supported versions

entity-framework/core/what-is-new/ef-core-9.0/breaking-changes.md
=> Add breaking change documentation for pending model changes

entity-framework/core/what-is-new/ef-core-8.0/breaking-changes.md
Addresses https://github.com/dotnet/efcore/issues/32394#issuecomment-2567564097
=> Add link with more information on Contains perf

entity-framework/core/querying/sql-queries.md, samples/core/Querying/SqlQueries/Program.cs
Our conceptual docs generally show SQL Server code, but the samples are designed to work against Sqlite (so they can run out of the box). Inlined sample code into the SQL querying page, which seems to be our general direction anyway.
Fixes #4919
=> Fix sample code in SQL querying page

entity-framework/core/modeling/entity-properties.md
@brentozar FYI
https://www.brentozar.com/archive/2025/01/i-feel-sorry-for-untrained-developers-using-entity-framework/
=> Fix wording

entity-framework/core/cli/dotnet.md, entity-framework/core/cli/powershell.md, entity-framework/core/learn-more/community-standups.md, entity-framework/core/miscellaneous/platforms.md, entity-framework/core/what-is-new/ef-core-5.0/plan.md, entity-framework/core/what-is-new/ef-core-6.0/plan.md, entity-framework/core/what-is-new/ef-core-7.0/plan.md, entity-framework/index.yml, entity-framework/toc.yml
Fixes dotnet/aspnetcore.docs#34327
Removing any references to Xamarin where needed for this repository and either replacing them with a reference to .NET MAUI if it makes sense or adding a note indicating more info on the Xamarin to .NET MAUI changes.
This is part of a sweep we are doing for all repos.
Any topic rewrites, significant updates needed are being tracked in new issues and handled separately.
=> Xamarin References Update

entity-framework/core/managing-schemas/migrations/managing.md
Aligns the file names in the examples to be consistent (include `Blog` in the file names).
=> Use consistent migration name in example

entity-framework/core/extensions/index.md
Based on the suggestion from @ErikEJ  in https://github.com/dotnet/efcore/issues/20592 I created this PR to add [my package](https://github.com/sander1095/EntityFrameworkCore.Extensions.SqlServer.DataMasking) (which adds data masking to SQL Server in EF Core) to the docs.
=> Add SanderTenBrinke.EntityFrameworkCore.Extensions.SqlServer.DataMasking as an EF Core extension and the outdated fork its based on

entity-framework/core/modeling/entity-properties.md
=> Tweak tab headings around NRTs in properties page

entity-framework/core/managing-schemas/scaffolding/templates.md
There isn't any parameter in the scaffolding command to include this type of Entity it is disabled by Default. This is required in cases where fine control of the generated SQL, keeping LINQ queries more TSQL like instead of C# like and others.
=> EF Scaffolding many to many join Entity

entity-framework/core/what-is-new/ef-core-10.0/whatsnew.md
We started pointing to Preview builds, but didn't remove the tip about dailies - fixing this now.
=> remove daily builds note from whats new

entity-framework/core/providers/sql-server/azure-sql-database.md
From https://github.com/dotnet/EntityFramework.Docs/pull/4899#issuecomment-2524704701.
=> Add note (from #4899).

entity-framework/core/providers/sql-server/index.md
From https://github.com/dotnet/EntityFramework.Docs/pull/4899#issuecomment-2524704701.
=> Document EnableRetryOnFailureByDefault (from #4899).

entity-framework/core/providers/cosmos/full-text-search.md, entity-framework/core/providers/cosmos/vector-search.md, entity-framework/core/what-is-new/ef-core-10.0/whatsnew.md
What's new docs for https://github.com/dotnet/efcore/issues/35476
=> Cosmos full-text search "what's new" docs

entity-framework/core/what-is-new/ef-core-10.0/whatsnew.md
Separating non-cosmos changes into another PR (this one), so that Cosmos folks don't need to look at irrelevant (to them) changes. Only review commit 2 onwards. Cosmos changes are here: https://github.com/dotnet/EntityFramework.Docs/pull/5009
=> Whats new preview4 - non cosmos changes

entity-framework/efcore-and-ef6/porting/index.md
I have seen a lot of confusion around when to perform the EF6->EF Core migration while migrating applications from framework to core. This adds a warning that EF6 is supported on all supported targets, while EF Core is only on .NET Core/.NET.
It also removes a comment around ApiPort that is no longer valid since that tool has been deprecated and is unavailable.
=> Highlight that migrating from EF6->EF Core requires being off .NET Framework

entity-framework/core/what-is-new/ef-core-10.0/whatsnew.md
See https://github.com/dotnet/efcore/pull/35835
=> Correct lazy loading perf issue title

samples/core/Querying/QueryFilters/NamedFilters.cs
I was reading about this awesome feature and noticed a typo in the query filter names.
=> Fixed typo in named query filter documentation

entity-framework/core/what-is-new/ef-core-10.0/whatsnew.md, entity-framework/toc.yml
Mostly @cincuranet's new translation mode fo parameterized collections.
This targets the WhatsNewPreview7 branch, so can be reviewed and merged immediately. We can do any further work/tweaks on that branch, and then merge it into live once preview.7 is out.
.NET-side release notes: https://github.com/dotnet/core/pull/9998
=> What's new docs for 10.0.0-preview.7

entity-framework/docfx.json
Update docfx.json with ms.update-cycle meta data reflecting current tiered support freshness cycle.
This setting is required by Learn and helps with reporting.
Fixes dotnet/aspnetcore.docs#35962
=> Update docfx.json with ms.update-cycle meta data

entity-framework/core/what-is-new/ef-core-8.0/whatsnew.md
There is a duplication of `the` in the article about what's new about EF Core 8.
=> docs: typo in ef-core-8.0 whats new

entity-framework/toc.yml
With RC1 out, it seems like the right time to point users directly towards the EF10 release notes (and breaking change notes) rather than towards EF9.
=> Point directly to EF10 release notes from TOC
