dotnet/EntityFramework.Docs

docs/index.rst, docs/modeling/configuring.rst, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/App.config, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/EFModeling.Configuring.FluentAPI.csproj, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Program.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Properties/AssemblyInfo.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Concurrency.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/IgnoreProperty.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/IgnoreType.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Index.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/IndexComposite.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/IndexUnique.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/KeyComposite.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/KeySingle.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/MaxLength.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relational/Column.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relational/DataType.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relational/DataTypeForProvider.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relational/NoValueGeneration.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relational/Table.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relational/TableAndSchema.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Required.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/packages.config, docs/modeling/configuring/sample/EFModeling.Configuring.sln, docs/modeling/default-conventions.rst, docs/modeling/index.rst
There is still some more work to be done, such as info about chaining multiple calls and the nested closure pattern, but this is an initial cut of the content that we can then add to.
Staged at: http://ef.readthedocs.org/en/staging/modelling/configuring.html
=> Initial cut of "Configuring Your Model"

docs/getting-started/full-dotnet.rst
We only require net45 (rather than net451)
Remove reference to VS2010 since it only supports net40
=> :bug: Fix requirements in Full .NET tutorial

docs/getting-started/osx.rst, docs/getting-started/x-plat/sample/global.json, docs/getting-started/x-plat/sample/src/ConsoleApp/Model.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Program.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/project.json
#4 
Should be available here http://ef.readthedocs.org/en/staging/getting-started/osx.html
The sample likely have some build and execution errors until DNX renames are finished. 
Please help me check for clarity, grammar, etc.
=> :memo: Getting started: OS X and DNX

docs/getting-started/linux.rst, docs/getting-started/osx.rst, docs/getting-started/x-plat/sample/src/ConsoleApp/Program.cs, docs/getting-started/xplat.rst
Reuses the sample from OS X. Only difference is the install instructions.
Fixes #5
Made some minor improvements to commands that make it clearer which folder to execute the commands in.
=> :memo: Getting started for Linux

docs/getting-started/linux.rst, docs/getting-started/osx.rst, docs/getting-started/x-plat/guide.rst, docs/getting-started/x-plat/issues.rst, docs/getting-started/x-plat/sample/.gitignore, docs/getting-started/x-plat/sample/src/ConsoleApp/Migrations/20150729221913_MyFirstMigration.Designer.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Migrations/20150729221913_MyFirstMigration.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Migrations/BloggingContextModelSnapshot.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Program.cs
Can remove workarounds when aspnet/EntityFramework#2357 and aspnet/EntityFramework#2545 are resolved.
=> Update OSX/Linux guides to include work arounds for issues in beta6

docs/getting-started/aspnet5.rst
``dnx database update`` should be ``dnx ef database update``
=> Typo in command syntax

docs/getting-started/aspnet5.rst, docs/getting-started/aspnet5/sample/src/EFGetStarted.AspNet5/project.json, docs/getting-started/full-dotnet.rst, docs/getting-started/full-dotnet/sample/EFGetStarted.ConsoleApp/EFGetStarted.ConsoleApp.csproj, docs/getting-started/full-dotnet/sample/EFGetStarted.ConsoleApp/packages.config, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/EFModeling.Configuring.FluentAPI.csproj, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/packages.config, docs/providers/index.rst
:watch: https://github.com/aspnet/EntityFramework/pull/3331
=> React to EF rename

.gitignore, docs/getting-started/linux.rst, docs/getting-started/osx.rst, docs/getting-started/x-plat/guide.rst, docs/getting-started/x-plat/issues.rst, docs/getting-started/x-plat/sample/global.json, docs/getting-started/x-plat/sample/src/ConsoleApp/Migrations/20151016182300_MyFirstMigration.Designer.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Migrations/20151016182300_MyFirstMigration.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Migrations/BloggingContextModelSnapshot.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Program.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/project.json
=> Update x-plat guides for beta8

docs/providers/index.rst
Bump up to .NET 4.5.1 required
=> Update index.rst to clarify .NET 4.5.1 requirement

docs/getting-started/linux.rst, docs/getting-started/osx.rst, docs/getting-started/x-plat/guide.rst, docs/getting-started/x-plat/issues.rst, docs/getting-started/x-plat/sample/global.json, docs/getting-started/x-plat/sample/src/ConsoleApp/Migrations/20151110200733_MyFirstMigration.Designer.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Migrations/20151110200733_MyFirstMigration.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Migrations/BloggingContextModelSnapshot.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Model.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/Program.cs, docs/getting-started/x-plat/sample/src/ConsoleApp/project.json
Use CoreCLR by default in the tutorials.
=> Update x-plat guide for RC1

docs/modeling/configuring/sample/EFModeling.Configuring.DataAnnotations/EFModeling.Configuring.DataAnnotations.csproj, docs/modeling/configuring/sample/EFModeling.Configuring.DataAnnotations/Samples/Relationships/ForeignKey.cs, docs/modeling/configuring/sample/EFModeling.Configuring.DataAnnotations/Samples/Relationships/InverseProperty.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/EFModeling.Configuring.FluentAPI.csproj, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relational/RelationshipConstraintName.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/CascadeDelete.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/CompositeForeignKey.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/CompositePrincipalKey.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/ForeignKey.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/Full.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/ManyToMany.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/NoForeignKey.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/OneNavigation.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/OneToOne.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/PrincipalKey.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Relationships/Required.cs, docs/modeling/configuring/sample/EFModeling.Conventions/EFModeling.Conventions.csproj, docs/modeling/configuring/sample/EFModeling.Conventions/Samples/Relationships/Full.cs, docs/modeling/configuring/sample/EFModeling.Conventions/Samples/Relationships/NoForeignKey.cs, docs/modeling/configuring/sample/EFModeling.Conventions/Samples/Relationships/OneNavigation.cs, docs/modeling/configuring/sample/EFModeling.Conventions/Samples/Relationships/OneToOne.cs, docs/modeling/index.rst, docs/modeling/relationships.rst
Note that this is not supposed to be a 100% exhaustive document of everything you can possibly do - since that would be a very large book. It's supposed to give folks the info they need to get started with the API. Our API docs provide all the specific little nuances of each variation of the API.
You can see the rendered version of the doc at http://ef.readthedocs.org/en/staging/modeling/relationships.html
=> :memo: Relationship docs

docs/getting-started/linux.rst
See https://github.com/aspnet/EntityFramework/issues/3794
=> Add note about requiring the native sqlite library on Linux

docs/getting-started/x-plat/issues.txt
See #80 and a few others.
cc @rowanmiller
=> Add issue to getting started guides about case-sensitive package names

docs/getting-started/osx.rst
cc @rowanmiller 
See https://github.com/dotnet/corefx/pull/4729#issuecomment-160761668
=> Bump minimum version of OSX

docs/cli/index.rst, docs/cli/powershell.rst, docs/index.rst
This matches the RC1 commands.
#78 
cc @rowanmiller
=> Document powershell commands

docs/cli/powershell.rst
Based on feedback https://github.com/aspnet/EntityFramework.Docs/issues/101#issuecomment-171230564
cc @natemcmaster
=> [TINY] Min PowerShell version in package manager console docs

docs/platforms/uwp/getting-started.rst
=> Add caution about using anonymous types to the UWP guide

docs/internals/services.rst
An overview of how EF uses services and dependency injection.
cc @rowanmiller @divega
=> Understanding EF Services

docs/platforms/aspnetcore/new-db.rst
Corrected a minor naming error.
=> Replaced BlogContext with BloggingContext

docs/cli/_common_errors.txt, docs/cli/dotnet.rst, docs/cli/powershell.rst, docs/miscellaneous/configuring-dbcontext.rst
This page is the target of the fwlink we want to add in https://github.com/aspnet/EntityFramework/pull/5312.
cc @rowanmiller
=> Add document with preview1 known issues for dotnet ef

docs/miscellaneous/configuring-dbcontext.rst
Changes:
- Samples show `DbContextOptions<T>` instead of non-generic option
- Separate the section about AddDbContext from explanation of constructor arg vs onconfiguring
cc @ajcvickers @rowanmiller
=> [rc2] Update configuring context guide

docs/providers/sql-compact/index.rst
Unsure about any changes to the platform name: "DNX/ASP.NET 5 (dnx451 only)"
=> Update SQL CE index.rst for RC2

docs/internals/services.rst
I update this guide to reflect the big changes we made in RC2 to isolate our internal services.
cc @ajcvickers @rowanmiller @divega
=> Update 'Understanding EF Services' for RC2

docs/miscellaneous/rc1-rc2-upgrade.rst
Without this space, the layout is broken
=> Only add a space between the code blocks

docs/miscellaneous/rc1-rc2-upgrade.rst
`DbSet<TEntity` -> `DbSet<TEntity>`
=> fixed a typo

docs/miscellaneous/rc1-rc2-upgrade.rst
cc @smitpatel @lucamorelli @rowanmiller
=> Document imports for RC2

docs/platforms/coreclr/sample/src/ConsoleApp/project.json
The latest version of "Microsoft.EntityFrameworkCore.Tools" Nuget library is 1.0.0-preview1-final.
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Tools/1.0.0-preview1-final
=> Updated the latest nuget library version.

docs/cli/dotnet.rst
=> Update .NET Core CLI doc for preview 2

docs/cli/dotnet.rst
Update document including explanation of workarounds and common errors.
=> Update dotnet-ef doc

docs/modeling/concurrency.rst, docs/modeling/configuring/sample/EFModeling.Configuring.DataAnnotations/Samples/Concurrency.cs, docs/modeling/configuring/sample/EFModeling.Configuring.FluentAPI/Samples/Concurrency.cs, docs/saving/concurrency.rst, docs/saving/index.rst, docs/saving/related-data.rst, docs/saving/sample/EFSaving/Concurrency/Sample.cs, docs/saving/sample/EFSaving/EFSaving.csproj, docs/saving/sample/EFSaving/Program.cs, docs/saving/sample/EFSaving/RelatedData/Sample.cs, docs/saving/sample/EFSaving/Transactions/ControllingTransaction/Sample.cs, docs/saving/sample/EFSaving/Transactions/ExternalDbTransaction/Sample.cs, docs/saving/sample/EFSaving/Transactions/SharingTransaction/Sample.cs, docs/saving/transactions.rst
Here is a local build of the content. To view it, download, unzip, open up html/index.html.
[html.zip](https://github.com/aspnet/EntityFramework.Docs/files/326677/html.zip)
The docs to be reviewed are:
* Saving Data -> Related Data
* Saving Data -> Concurrency Conflicts
* Saving Data -> Transactions
=> Adding some "Saving" articles

docs/index.rst, docs/querying/basic.rst, docs/querying/client-eval.rst, docs/querying/index.rst, docs/querying/overview.rst, docs/querying/raw-sql.rst, docs/querying/related-data.rst, docs/querying/tracking.rst, samples/Querying/Querying/App.config, samples/Querying/Querying/Basics/Sample.cs, samples/Querying/Querying/Blog.cs, samples/Querying/Querying/BloggingContext.cs, samples/Querying/Querying/ClientEval/Sample.cs, samples/Querying/Querying/ClientEval/ThrowOnClientEval/BloggingContext.cs, samples/Querying/Querying/Person.cs, samples/Querying/Querying/PersonPhoto.cs, samples/Querying/Querying/Post.cs, samples/Querying/Querying/Program.cs, samples/Querying/Querying/Properties/AssemblyInfo.cs, samples/Querying/Querying/Querying.csproj, samples/Querying/Querying/RawSQL/Sample.cs, samples/Querying/Querying/RelatedData/Sample.cs, samples/Querying/Querying/RelatedData/ThrowOnIgnoredInclude/BloggingContext.cs, samples/Querying/Querying/Tracking/Sample.cs, samples/Querying/Querying/packages.config, samples/Samples.vs2015.sln
Here is a local build of the content. To view it, download, unzip, open up html/index.html.
[html.zip](https://github.com/aspnet/EntityFramework.Docs/files/332575/html.zip)
The new content under the "Querying Data" section from the left menu of the site. All pages should be reviewed, as it is all new.
cc @anpete @ajcvickers as it would be good to get your eyes over this
=> Add "Querying Data" section

docs/_shared/intro.txt, docs/index.rst, docs/intro.rst
Provide a landing page that covers what EF is, and directs off to the
various parts of the docs.
Using shared content rendered on two pages so that it shows up on the
"index" page, but also has a node in the left menu.
=> Landing page

docs/miscellaneous/connection-strings.rst, docs/miscellaneous/index.rst
=> Connection string guidance

.github/ISSUE_TEMPLATE.md
=> Add issue template for EF.Docs

docs/_shared/intro.txt, docs/providers/devart/index.rst, docs/providers/ibm/index.rst, docs/providers/in-memory/index.rst, docs/providers/npgsql/index.rst, docs/providers/oracle/index.rst, docs/providers/sql-compact/index.rst, docs/providers/sql-server/index.rst, docs/providers/sqlite/index.rst
Also tidying up some of the provider docs to use a more consistent format etc.
=> More visible docs on installing

docs/_shared/intro.txt
You have not created "context" in the using statement, you created "db"
=> on line #62, change "context" to "db"

docs/platforms/aspnetcore/existing-db.rst, docs/platforms/aspnetcore/new-db.rst, docs/platforms/full-dotnet/existing-db.rst, docs/platforms/full-dotnet/new-db.rst, docs/platforms/uwp/getting-started.rst
Web Application is no longer the default template, so adding
instructions to select it.
Updating all tutorials to require VS2015 Update 3 (and providing a link
to it).
Fixes #214
=> [TINY] Minor tweaks to RTM tutorials

docs/platforms/aspnetcore/_static/reverse-engineer-command.txt, docs/platforms/aspnetcore/existing-db.rst, docs/platforms/full-dotnet/_static/reverse-engineer-command.txt, docs/platforms/full-dotnet/existing-db.rst
Ensures that files end up in the Models folder
Also moving to an inline code snippet rather than a file include
Fixes #217
=> [TINY] Specify output dir in ASP.NET tutorial

docs/modeling/included-types.rst, samples/Modeling/Conventions/Samples/IncludedTypes.cs
Remove the unneeded Fluent API calls to get a type included in the
model.
Fixes aspnet/EntityFramework/5855
=> [TINY] Simplify "Included Types" code sample

docs/platforms/uwp/getting-started.rst
This walkthrough uses SQLite, not SQL Server.
=> Changed SQL Server to SQLite

docs/modeling/index.rst
=> Fix samples tip link

docs/querying/raw-sql.rst
=> Fixed typo

docs/querying/tracking.rst
=> Add note about tracking use for nav property fix-up

docs/providers/sqlite/index.rst
Instead of `hhttps` use `https`
=> Fix nuget link

docs/providers/_shared/third-party-provider-disclaimer.txt, docs/providers/devart/index.rst, docs/providers/ibm/index.rst, docs/providers/mysql/index.rst, docs/providers/npgsql/index.rst, docs/providers/sql-compact/index.rst
Calling out that they may have different quality, licensing, support etc. than EF Core itself
cc @divega for review
=> Add a note to third party providers

docs/platforms/aspnetcore/index.rst
=> Link to tutorial on ASP.NET site

docs/modeling/alternate-keys.rst
Resolves aspnet/EntityFramework/issues/6644
=> :memo: Better clarify that alternate key != unique index

docs/modeling/shadow-properties.rst
Fixes aspnet/EntityFramework/issues/6655
=> Fix shadow FK naming docs

entity-framework-core/efcore-vs-ef6/index.md, entity-framework-core/miscellaneous/index.md, entity-framework-core/toc.md
I also removed the _Files too.
=> Migration qa - index/toc fixes

entity-framework/core/providers/pomelo/index.md
=> Changing the letter case

entity-framework/core/extensions/index.md, entity-framework/core/extensions/llbl-gen-pro.md, entity-framework/toc.md
Added Tools & Extensions section and info about LLBLGen Pro
=> Add LLBLGen Pro Info

entity-framework/core/extensions/efcore-practices.md, entity-framework/core/extensions/efsecondlevelcache-core.md, entity-framework/core/extensions/entityframeworkcore-detached.md, entity-framework/core/extensions/entityframeworkcore-primarykey.md, entity-framework/core/extensions/entityframeworkcore-rx.md, entity-framework/core/extensions/entityframeworkcore-triggers.md, entity-framework/core/extensions/entityframeworkcore-typedoriginalvalues.md, entity-framework/toc.md
=> Adding various extensions (all available on Nuget)

samples/core/Saving/Saving/RelatedData/Sample.cs
var blog = new Blog { Url = "http://blogs.msdn.com/visualstudio" };
var post = context.Posts.First();
post.Blog = blog;
context.SaveChanges();
=> Changing relationships issues alternative soluton

entity-framework/core/querying/async.md, entity-framework/core/saving/async.md, entity-framework/toc.md, samples/core/Querying/Querying/Async/Sample.cs, samples/core/Querying/Querying/Querying.csproj, samples/core/Saving/Saving/Async/Blog.cs, samples/core/Saving/Saving/Async/BloggingContext.cs, samples/core/Saving/Saving/Async/Post.cs, samples/core/Saving/Saving/Async/Sample.cs, samples/core/Saving/Saving/Program.cs, samples/core/Saving/Saving/Saving.csproj
=> Add info about async query & save

entity-framework/core/extensions/entityframeworkcore-detached.md
=> library rename

entity-framework/core/querying/related-data.md, samples/core/Querying/Querying/Post.cs, samples/core/Querying/Querying/PostTag.cs, samples/core/Querying/Querying/Querying.csproj, samples/core/Querying/Querying/RelatedData/Sample.cs, samples/core/Querying/Querying/Tag.cs
As requested in https://github.com/aspnet/EntityFramework/issues/3692#issuecomment-279282322
cc @tinchou for review
=> Add Include example with multiple leaf nodes

entity-framework/core/get-started/full-dotnet/index.md, entity-framework/core/miscellaneous/connection-strings.md, entity-framework/core/providers/sql-server/index.md, entity-framework/efcore-and-ef6/choosing.md
=> full .NET --> .NET Framework

entity-framework/core/get-started/netcore/new-db-sqlite.md
[Review URL](https://review.docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite?branch=Rick-Anderson-patch-1)
~~EF Folks, wait for @tdykstra reviews before you waste time on review~~
=> SQLLite new DB doc

build.sh
Changing a path that was outdated. But not at all sure that this is the right solution.
=> Update build.sh to fix travis

entity-framework/core/platforms/index.md
Attempt to fix table layout as rendered in docs.microsoft.com.
=> Fix platforms table

entity-framework/core/modeling/relational/unique-constraints.md
Link to doc page: https://docs.microsoft.com/en-us/ef/core/modeling/relational/unique-constraints
=> Add missing trailing brace

entity-framework/core/what-is-new/index.md, entity-framework/index.md
- new home page
- removing reference to preview 2 in what is new
=> Updates from master

entity-framework/core/get-started/uwp/getting-started.md
Added ms.topic metadata so this topic properly shows up in reporting as a get-started-article.
=> Added topic type metadata

entity-framework/core/get-started/aspnetcore/new-db.md
Added ms.topic metadata so this topic shows up properly in reporting as a get-started-article
=> Added ms.topic metadata

entity-framework/core/platforms/index.md
For background on this see https://docs.microsoft.com/en-us/dotnet/standard/glossary#platform
=> platform --> .net implementation

.openpublishing.publish.config.json
Just noticed with my last PR that I couldn't see the results on the review site. This configuration enables that.
=> enable to preview content on review site

entity-framework/core/modeling/dynamic-model.md, entity-framework/toc.md, samples/core/DynamicModel/ConfigurableEntity.cs, samples/core/DynamicModel/DynamicContext.cs, samples/core/DynamicModel/DynamicModel.csproj, samples/core/DynamicModel/DynamicModelCacheKeyFactory.cs, samples/core/DynamicModel/Program.cs, samples/core/Samples.sln
=> Add a page for IModelCacheKeyFactory

entity-framework/core/modeling/relational/data-types.md, samples/core/Modeling/DataAnnotations/Samples/Relational/DataType.cs, samples/core/Modeling/FluentAPI/Samples/Relational/DataType.cs
=> Add a sample showing how to configure scale and precision

entity-framework/core/miscellaneous/connection-resiliency.md, samples/core/Miscellaneous/ConnectionResiliency/Program.cs
=> Update Connection Resiliency docs

entity-framework/core/miscellaneous/1x-2x-upgrade.md
=> Mention design-time working directory in 2.0 upgrade notes

entity-framework/core/modeling/backing-field.md, entity-framework/core/modeling/concurrency.md, entity-framework/core/modeling/shadow-properties.md, samples/core/Modeling/DataAnnotations/Samples/Concurrency.cs, samples/core/Modeling/DataAnnotations/Samples/Timestamp.cs, samples/core/Modeling/FluentAPI/Samples/Concurrency.cs, samples/core/Modeling/FluentAPI/Samples/Timestamp.cs
=> Several smaller updates to docs

entity-framework/core/managing-schemas/index.md, entity-framework/core/managing-schemas/migrations.md, entity-framework/core/managing-schemas/scaffolding.md, entity-framework/toc.md
This will contain the Migrations and Reverse Engineering documentation.
cc @smitpatel
=> Stub the "Managing Database Schemas" section

entity-framework/core/providers/pomelo/index.md
=> Update pomelo provider get start docs

entity-framework/core/miscellaneous/cli/dbcontext-creation.md, entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/cli/index.md, entity-framework/core/miscellaneous/cli/powershell.md, entity-framework/core/miscellaneous/cli/services.md, entity-framework/toc.md
=> Update EF Core Tools documentation

entity-framework/core/managing-schemas/ensure-created.md, entity-framework/core/managing-schemas/index.md, entity-framework/core/managing-schemas/migrations/history-table.md, entity-framework/core/managing-schemas/migrations/index.md, entity-framework/core/managing-schemas/migrations/operations.md, entity-framework/core/managing-schemas/migrations/projects.md, entity-framework/core/managing-schemas/migrations/providers.md, entity-framework/core/managing-schemas/migrations/teams.md, entity-framework/toc.md
=> Document Migrations

entity-framework/efcore-and-ef6/porting/port-edmx.md
Link to existing tutorial page to help on making the point clearer.
=> Add a link to a existing document

entity-framework/core/managing-schemas/migrations/providers.md
Fixed Typo in providers.md to avoid confusion.
=> fixed typo in providers.md

entity-framework/core/querying/raw-sql.md
Fixes https://github.com/aspnet/EntityFramework.Docs/issues/585
=> FromSql should be given as composable SQL

entity-framework/core/querying/raw-sql.md
Additions to the fix for #585. 
cc @gfoidl
=> More details on raw-sql composability paragraph

entity-framework/core/managing-schemas/migrations/index.md, entity-framework/core/miscellaneous/1x-2x-upgrade.md, entity-framework/core/miscellaneous/cli/dbcontext-creation.md, entity-framework/core/miscellaneous/configuring-dbcontext.md
Adds more context around design-time discovery.
=> Improvements to configuring-DbContext

entity-framework/core/modeling/relational/inheritance.md
Many people are looking for TPT or TPC, that way it is clear in the documentation, without having to search GitHub issues.
=> Added a note explaining TPH/TPT/TPC status

entity-framework/core/querying/related-data.md
=> Adding a note on ThenInclude about Roslyn bug

entity-framework/core/modeling/value-conversions.md, entity-framework/toc.md
=> Value conversion docs

entity-framework/core/modeling/constructors.md, entity-framework/core/modeling/value-conversions.md, entity-framework/core/querying/related-data.md, entity-framework/toc.md
=> Constructor and lazy-loading docs for preview1

entity-framework/core/modeling/relational/indexes.md, samples/core/Modeling/FluentAPI/FluentAPI.csproj, samples/core/Modeling/FluentAPI/Samples/Relational/IndexFilter.cs, samples/core/Modeling/FluentAPI/Samples/Relational/IndexNoFilter.cs
=> Add documentation for index filters

.gitignore, entity-framework/core/modeling/data-seeding.md, entity-framework/core/modeling/dynamic-model.md, entity-framework/core/modeling/value-conversions.md, entity-framework/toc.md, samples/core/DataSeeding/Blog.cs, samples/core/DataSeeding/DataSeeding.csproj, samples/core/DataSeeding/DataSeedingContext.cs, samples/core/DataSeeding/Post.cs, samples/core/DataSeeding/Program.cs, samples/core/Samples.sln
=> Add documentation for data seeding

entity-framework/core/saving/transactions.md, samples/core/Saving/Saving/Saving.csproj, samples/core/Saving/Saving/Transactions/AmbientTransaction/Sample.cs, samples/core/Saving/Saving/Transactions/CommitableTransaction/Sample.cs, samples/core/Saving/Saving/Transactions/SharingTransaction/Sample.cs, samples/core/Saving/Saving/packages.config
=> Add docs for System.Transactions

entity-framework/core/modeling/owned-entities.md, entity-framework/core/what-is-new/ef-core-2.0.md, entity-framework/toc.md
This is based on @julielerman's PR #469, but incorporating changes from @AndriySvyryd and my own feedback, changes in 2.1, etc.
Fixes #466.
=> Owned entity types documentation reborn

entity-framework/core/modeling/constructors.md
I think you meant "setters" in first point of Read-only properties section.
=> Fix Read-only properties description

.gitignore, entity-framework/core/modeling/concurrency.md, entity-framework/core/saving/concurrency.md, samples/core/Saving/Saving/Concurrency/Sample.cs
[Review URL](https://review.docs.microsoft.com/en-us/ef/core/saving/concurrency?branch=pr-en-us-572)
[Handling Concurrency](https://docs.microsoft.com/en-us/ef/core/saving/concurrency)
* Shortened long sentences so machine translation will work.
* Removed copy/paste sample, use sample in repo.
* Format sample in repo so code is readable on typical notebook screen.
* Added a couple comments to build sample (required NuGet).
* No code changes made other than comments, formatting.
* Removed obnoxious TIP that obscures link.
=> Clean up concurrency doc/format code

entity-framework/index.md
for task 1199273 per Sarah Barrett
=> add ms.topic metadata value

entity-framework/core/modeling/data-seeding.md
When attempting to learn from this sample, I was unaware that EnsureCreated() needed to be called. Better clarification would be of value.
=> Add EnsureCreated() details

entity-framework/core/modeling/data-seeding.md
Mentions you can also use EnsureCreated, and some caveats. 
Related to https://github.com/aspnet/EntityFramework.Docs/issues/690.
=> Further clarification on when seed data is saved

entity-framework/core/miscellaneous/cli/dotnet.md
=> Update .NET CLI reference installation instructions

entity-framework/core/querying/related-data.md
To reflect the fact that we moved it to the Abstractions package.
=> Update ILazyLoader coupling level

entity-framework/core/platforms/index.md
=> Fixed an "active issues" link in the Mono & Xamarin compatibility footnote

entity-framework/core/what-is-new/ef-core-2.0.md
an incorrect semicolon that stops it compiling
=> fix broken EF.Functions.Like snippet

samples/core/Saving/Saving/Transactions/AmbientTransaction/Sample.cs, samples/core/Saving/Saving/Transactions/ExternalDbTransaction/Sample.cs
Some of the transaction-related samples create a new SqlConnection and call the Open() method before passing it to a DbContext. After discussing the issue on [StackOverflow](https://stackoverflow.com/questions/51239326/do-i-need-to-close-the-dbconnection-manually-when-using-ambient-transactions-wit#51239326), I think in that case the connection should also be closed by the caller.
=> Added using-blocks to manually opened connections in transaction samples

entity-framework/ef6/querying/index.md
Hello, @divega ,
Translator has reported possible source content issue. 
"Fixing link's displaying text"
Please review and merge the suggested proposed file change to avoid this error. If you make related fix in another PR, then share your PR number, so we can confirm and close this PR.
=> M27741: Fixing hyperlink text

entity-framework/core/get-started/full-dotnet/existing-db.md
.NET 4.5.1 and early versions of VS 2017 will not work
=> Update to current prerequisites

entity-framework/core/modeling/query-types.md
=> Fix broken link to GitHub sample

entity-framework/core/managing-schemas/migrations/operations.md
=> Add default return statement

entity-framework/core/get-started/netcore/new-db-sqlite.md
[Review link](https://review.docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite?branch=pr-en-us-890)
=> Minor changes to console app new db SQLite walkthrough

entity-framework/core/miscellaneous/cli/dbcontext-creation.md
"Tools ... try"
Assumed it should not be "Tool ... tries" based on previous sentences.
=> Fixed subject/verb number agreement

entity-framework/core/providers/provider-log.md
Issue https://github.com/aspnet/EntityFrameworkCore/issues/11198
=> Create page for log of provider-impacting changes

entity-framework/ef6/get-started.md
=> Typo fix (#911)

entity-framework/core/modeling/constructors.md, entity-framework/core/modeling/value-conversions.md
Also changing "Csharp cast" to "type cast" in value conversions topic.
=> Changing Csharp to csharp in constructors topic to improve snippets

entity-framework/core/what-is-new/roadmap.md
=> Update roadmap with information about 2.2 and 3.0

entity-framework/ef6/modeling/code-first/data-annotations.md
Fix grammar, spelling, and formatting.
=> Fix grammar, spelling, and formatting

entity-framework/ef6/fundamentals/databinding/winforms.md
=> Fixing missing null coalescing operator

entity-framework/core/saving/cascade-delete.md, samples/core/Saving/Saving/CascadeDelete/Sample.cs
=> Cascade delete samples show incorrect id (fix for #899)

entity-framework/core/get-started/aspnetcore/new-db.md
Updated the repo link to point to the correct repo. Previous link was returning a 404.
=> Broken link for [.NET Core CLI with SQLite] sample

entity-framework/core/modeling/index.md
ln39 overwritten => overridden
I'd also like to link to the Data Annotations documentation here.
=> Change phrasing

entity-framework/ef6/modeling/code-first/workflows/new-database.md
All topics should only have one H1
=> fix header level

entity-framework/core/miscellaneous/1x-2x-upgrade.md
=> Fix broken link and simplify upgrade to EF Core 2

entity-framework/ef6/modeling/code-first/migrations/index.md
you application => your application
=> Updated one-letter typo in first sentence

entity-framework/core/querying/overview.md
Tried to improve the grammar and readability.
Fixes #988
=> Issue #988 - Grammer correction

entity-framework/ef6/fundamentals/databinding/wpf.md
Localization team has reported source content issue that causes issue for localization. 
Description: The link doesn't seem to work anyway. So either it is needed to update the link or place it in the box. Also there are extra asterisks, which werent reported as a bug (LOC and ENU is matching).
Please review the comment tag added and reply with explanation if fix is needed or not. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
=> C42263: Broken hyperlink

entity-framework/core/get-started/install/index.md
Corrected the title of the page to Installing Entity Framework Core
=> Fixed typo in title "Installing Entiy Framework Core"

entity-framework/core/get-started/aspnetcore/new-db.md, entity-framework/core/get-started/netcore/new-db-sqlite.md
The previous link doesn't help too much.
=> Update link to migrations doc

entity-framework/core/managing-schemas/migrations/index.md
=> Edit pass on Migrations article

entity-framework/core/get-started/netcore/new-db-sqlite.md
See the broken link here: https://docs.microsoft.com/ef/core/get-started/netcore/new-db-sqlite
=> Fixed link Markdown formatting

entity-framework/core/get-started/netcore/new-db-sqlite.md
Found out this while reading the documentation.
=> Fixed missing link bracket

entity-framework/ef6/querying/load-method.md
=> Add missing parentheses

entity-framework/core/miscellaneous/configuring-dbcontext.md
Addresses comments received on the doc as reported in #876
=> Add package and using statement info to DbContext Configure topic

entity-framework/core/managing-schemas/ensure-created.md, entity-framework/toc.md
=> Document Database.EnsureCreated() and friends

entity-framework/core/managing-schemas/ensure-created.md, entity-framework/core/modeling/spatial.md, entity-framework/efcore-and-ef6/index.md, entity-framework/toc.md
=> Document using spatial data on EF Core

entity-framework/core/get-started/aspnetcore/existing-db.md, entity-framework/core/get-started/full-dotnet/existing-db.md, entity-framework/core/managing-schemas/scaffolding.md, entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/cli/powershell.md, entity-framework/toc.md
=> Document Reverse Engineering

entity-framework/core/extensions/index.md
Addition of information for CatFactory GitHub repository and description for project.
=> Addition of information for CatFactory

entity-framework/core/get-started/install/index.md
I am trying to make them less version-specific but clearer at the same time.
Fixes #1155.
=> Update installation instructions

entity-framework/core/extensions/index.md
cc @pwelter34. Let us know if there is anything you would like added or edited. I intend to merge this today.
=> Add efg to tools and extensions page

entity-framework/core/querying/raw-sql.md
A period was missing from one of the statements in the "Passing Parameters" section.
=> Added the missing period "."

entity-framework/ef6/fundamentals/async.md
Fixed example code to match output displayed on syncoutput.png.
=> Example Code Screenshot mismatch

entity-framework/core/modeling/owned-entities.md
=> Fix spelling

entity-framework/ef6/fundamentals/async.md
Hello @divega,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
=> C63820: Nested asterisks issue

entity-framework/core/get-started/netcore/new-db-sqlite.md, entity-framework/core/index.md
=> Add open source as distinctive feature

entity-framework/core/miscellaneous/connection-resiliency.md
I think it can be useful for many devs.
=> Add example for ASP.NET Core application

entity-framework/ef6/modeling/code-first/data-annotations.md
Removed the extra word "will" from the statement "but code first will create four will foreign key properties:" to read "but code first will create four foreign key properties:".
=> Fixed sentence regarding InverseProperty

entity-framework/core/what-is-new/ef-core-3.0/features.md
Many to many is hands down the top issue on the EF Core sorted by most commented and most reacted.
- [Most commented](https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc)
- [Most upvotes](https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)
=> Updated issue link

entity-framework/core/querying/raw-sql.md
Update Limitations section to reflect issue with name mapping vs. order mapping from stored procedure.
=> Update Limitations reference Named Mapping

entity-framework/core/miscellaneous/cli/powershell.md
Copied from https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md
=> Correct docs for `Get-DbContext`

entity-framework/core/providers/provider-log.md
(PR for validation; will merge without review.)
=> Provider impacting changes

CONTRIBUTING.md
1. Changed the introduction with active voice and edited repetition.
2. Edited repetition for faster understanding.
3. Erased unnecessary word "which is". 
4. Typo in word. Should be plural form.
5. Edited to concise sentence 
6.   Edited run-on sentences.
Thank you for consideration.
=> Edited CONTRIBUTING.md for better readability

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
Describes changes from PR https://github.com/aspnet/EntityFrameworkCore/pull/15232
=> Breaking change note on Task->ValueTask

entity-framework/core/managing-schemas/migrations/index.md
=> Update migration timestamp in documentation

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
I talked to @ajcvickers and he also thought it is a good idea to have a note about this. cc @AndriySvyryd.
=> Note about configuring property names for field-only properties

entity-framework/core/modeling/included-properties.md, entity-framework/core/modeling/included-types.md, entity-framework/core/modeling/index.md, entity-framework/core/modeling/keys.md, entity-framework/core/modeling/max-length.md, entity-framework/core/modeling/relational/columns.md, entity-framework/core/modeling/relationships.md, entity-framework/core/modeling/required-optional.md
=> Indicate where Data Annotations can be found.

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
Closes https://github.com/aspnet/EntityFrameworkCore/issues/14016.
=> Breaking change note for removal of dotnet ef from SDK

entity-framework/core/what-is-new/roadmap.md
Just found one thing I wanted to tweak. The main goal is to try the Acrolinx extension that has been setup for us.
=> Tweak release planning process

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
"EF Core" was left out inadvertently from the description paragraph under "New behavior"
=> Tracking Issue #12430

entity-framework/core/modeling/constructors.md
Change to clarify model constructor access modifier required when using Lazy Loading Proxies #984
=> Resolve Issue #984 constructors.md

entity-framework/toc.md
Fixes https://github.com/aspnet/EntityFramework.Docs/issues/1439
/cc: @CamSoper
=> Add MS Learn module link to ToC

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
Based on a conversation in #1483.
=> Fixes sentence.

entity-framework/core/modeling/relationships.md, samples/core/Modeling/FluentAPI/Samples/Relationships/NoNavigation.cs
=> feat(relationships): add "without navigation property" section

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
For https://github.com/aspnet/EntityFrameworkCore/issues/15704
/cc @divega @ajcvickers
=> Breaking change note on FromSql* on DbSet<>

entity-framework/ef6/saving/change-tracking/property-values.md
=> Fix typo in sample for EF6 change tracking

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
=> Remove unrelated code sample

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
See https://github.com/aspnet/EntityFrameworkCore/issues/16400
=> Add note about UseRowNumberForPaging

samples/core/QueryTypes/Program.cs
to fix: https://github.com/aspnet/EntityFramework.Docs/issues/793
=> Add DbQuery Region

entity-framework/core/modeling/query-types.md
fixes issue: https://github.com/aspnet/EntityFramework.Docs/issues/793
dependent upon PR: https://github.com/aspnet/EntityFramework.Docs/pull/1592
=> Add DbQuery

entity-framework/core/get-started/aspnetcore/existing-db.md
This PR is to help fix the preview builds site.
[Internal bug](https://icm.ad.msft.net/imp/v3/incidents/details/133793474/home)
[Internal review URL](https://review.docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db?branch=pr-en-us-1587) which 404's
=> DO NOT MERGE

entity-framework/core/miscellaneous/cli/dotnet.md
The `$` was not part of the command.
=> Fix dotnet ef command sample

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
* .NET Standard 2.1
* No identity resolution in no-tracking queries
=> Add breaking changes

entity-framework/ef6/querying/related-data.md
=> fixed plural typo

samples/core/Miscellaneous/Testing/TestProject/InMemory/BlogServiceTests.cs, samples/core/Miscellaneous/Testing/TestProject/SQLite/BlogServiceTests.cs
=> missing SaveChanges in Add_writes_to_database

entity-framework/ef6/fundamentals/databinding/winforms.md
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Description: Reporting source issues as a result of nested asterisks (i.e. \*\*\* instead of \*\*\_) that are breaking code in localized sites.
=> C113614: Changing italic asterisks by italic underscore

entity-framework/core/querying/filters.md
=> Add note on multiple query filters not being supported

entity-framework/core/what-is-new/ef-core-3.0/features.md
As the feature was punted for 3.0
=> Remove new feature note on property bag entities

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-3.0/features.md, entity-framework/core/what-is-new/ef-core-3.0/index.md, entity-framework/core/what-is-new/index.md, entity-framework/toc.md
- Add back postponed features to call out that they were postponed
- Rewrite finished features to reflect that they are finished
- Remove "preview"
Fixes #1602, #1598, #1523
=> Update roadmap and list of new features in EF Core 3.0

entity-framework/ef6/querying/related-data.md
Hide whitespace changes for easier diff.
=> Improve markdown and make use of [!NOTE]

entity-framework/core/modeling/owned-entities.md, entity-framework/core/modeling/relational/data-types.md, entity-framework/core/modeling/required-optional.md, entity-framework/core/modeling/table-splitting.md, entity-framework/core/providers/cosmos/index.md, entity-framework/core/what-is-new/ef-core-2.0.md, entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-3.0/features.md, samples/core/Modeling/OwnedEntities/Distributor.cs, samples/core/Modeling/OwnedEntities/OwnedEntities.csproj, samples/core/Modeling/OwnedEntities/OwnedEntityContext.cs, samples/core/Modeling/TableSplitting/DetailedOrder.cs, samples/core/Modeling/TableSplitting/Order.cs, samples/core/Modeling/TableSplitting/Program.cs, samples/core/Modeling/TableSplitting/TableSplitting.csproj, samples/core/Modeling/TableSplitting/TableSplittingContext.cs
Fixes #1518
Fixes #1646
Fixes #1692
Fixes #772
=> Update owned types documentation for 3.0

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
=> Change the impact of "DetectChanges honors store-generated key values" to high

entity-framework/core/what-is-new/ef-core-3.0/features.md, entity-framework/ef6/what-is-new/index.md
=> Improve what's new in 3.0 

entity-framework/core/miscellaneous/logging.md
=> Update logging snippets for 3.0

entity-framework/core/miscellaneous/cli/dbcontext-creation.md
=> Document Program.CreateHostBuilder()

entity-framework/toc.yml
Added new NRT page to TOC (left out from #1709).
=> Add NRT page to TOC

entity-framework/core/modeling/keyless-entity-types.md
=> Fixes sample link

entity-framework/core/get-started/install/index.md
Added Hyper links for Visual Studio, Visual Studio for Mac, and Visual Studio Code for easy redirection.
=> Added hyperlinks

entity-framework/core/what-is-new/ef-core-3.0/index.md
=> Correct await foreach pattern

entity-framework/core/querying/related-data.md
Am leaving #1769 open to possibly discuss cartesian explosion further and include a sample of how to break down queries with lots of includes.
@smitpatel note the removal of the section on ignored includes. I wasn't in the discussions around this so I hope it's the right thing (the warning itself has been deprecated, plus note that the doc samples mistakenly showed the client evaluation warning).
* Added note on Include producing JOINs in 3.0 and on the cartesian   explosion problem.
* Remove warning for VS Intellisense issue which has been fixed (https://github.com/dotnet/roslyn/issues/8237).
* Removed the ignored include section
* Removed some old "introduced in version" notes
Closes #1466
=> Cleanup in related data page

entity-framework/core/providers/cosmos/index.md, entity-framework/core/providers/in-memory/index.md, entity-framework/core/providers/index.md, entity-framework/core/providers/sql-server/index.md, entity-framework/core/providers/sql-server/memory-optimized-tables.md, entity-framework/core/providers/sqlite/index.md
* Added .NET Core CLI installation instructions, in tabs.
* Cosmos provider no longer in preview
* Removed outdated "introduced in 1.1" note
Closes #1770
=> Minor improvements to provider docs

entity-framework/core/miscellaneous/1x-2x-upgrade.md
=> Correct links in 1x-2x-upgrade page

entity-framework/core/get-started/index.md, entity-framework/core/managing-schemas/ensure-created.md, entity-framework/core/miscellaneous/nullable-reference-types.md, entity-framework/core/modeling/relational/indexes.md, entity-framework/core/querying/raw-sql.md, entity-framework/ef6/modeling/designer/stored-procedures/cud.md
- Missing alerts
Also bunch of warnings from authoringpack in VS.
=> Correct errors from CATS report

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
=> Breaking change note on duplicated results in Include

entity-framework/ef6/querying/local-data.md
Fix for syntax error in code sample for title "Using Local to add and remove entities from the context  "
=> Fix for syntax error in code sample in local-data.md

entity-framework/core/providers/sqlite/limitations.md
Fix typo in use of "support" instead of "supported"
=> Fix typo limitations.md

entity-framework/core/querying/raw-sql.md, samples/core/Querying/RawSQL/Sample.cs
=> Update Raw Sql query documentation

entity-framework/ef6/fundamentals/performance/ngen.md
For 64 bit run was showing up as code instead of text
=> fix formatting

entity-framework/core/miscellaneous/configuring-dbcontext.md
=> Some more details on configuring DbContext

samples/core/CompiledQueries/CompiledQueries.csproj, samples/core/Cosmos/Cosmos.csproj, samples/core/DbContextPooling/DbContextPooling.csproj, samples/core/DynamicModel/DynamicModel.csproj, samples/core/GetStarted/EFGetStarted.csproj, samples/core/KeylessEntityTypes/KeylessEntityTypes.csproj, samples/core/Miscellaneous/ConnectionResiliency/ConnectionResiliency.csproj, samples/core/Miscellaneous/Logging/Logging/Logging.csproj, samples/core/Miscellaneous/NullableReferenceTypes/NullableReferenceTypes.csproj, samples/core/Miscellaneous/Testing/BusinessLogic/BusinessLogic.csproj, samples/core/Miscellaneous/Testing/TestProject/TestProject.csproj, samples/core/Modeling/Conventions/Conventions.csproj, samples/core/Modeling/DataAnnotations/DataAnnotations.csproj, samples/core/Modeling/DataSeeding/DataSeeding.csproj, samples/core/Modeling/FluentAPI/FluentAPI.csproj, samples/core/Modeling/OwnedEntities/OwnedEntities.csproj, samples/core/Modeling/TableSplitting/TableSplitting.csproj, samples/core/QueryFilters/QueryFilters.csproj, samples/core/Saving/Saving.csproj
=> Update samples to depend on 3.0.0 GA

entity-framework/ef6/what-is-new/index.md
Full stops were missing from few lines, fixed that.
=> Added full stops at the end of lines

entity-framework/ef6/index.md
Added hyperlink to LINQ for easy redirection
=> Added hyperlink to LINQ for easy redirection

entity-framework/ef6/index.md
For easy redirection, added hyperlink to Entity Framework Tools for Visual Studio under Get Started section.
=> Added hyperlink for easy redirection

entity-framework/core/modeling/spatial.md
As of version 3.0.0, the following are translated:
- Buffer(double, int)
- InteriorPoint
- IsWithinDistance
- OgcGeometryType
- Union()
=> Updated spatial data translations for Npgsql

entity-framework/core/modeling/data-seeding.md, entity-framework/core/providers/cosmos/index.md, entity-framework/core/providers/cosmos/limitations.md, entity-framework/core/providers/cosmos/unstructured-data.md, entity-framework/core/what-is-new/ef-core-2.2.md, entity-framework/ef6/fundamentals/providers/index.md, entity-framework/ef6/get-started.md, entity-framework/ef6/index.md, entity-framework/ef6/resources/glossary.md, entity-framework/ef6/what-is-new/past-releases.md, samples/core/Cosmos/Cosmos.csproj, samples/core/Cosmos/ModelBuilding/Order.cs, samples/core/Cosmos/ModelBuilding/OrderContext.cs, samples/core/Cosmos/ModelBuilding/Sample.cs, samples/core/Cosmos/UnstructuredData/Sample.cs
=> Update Cosmos docs

entity-framework/core/extensions/index.md
The traffic I got from this entry made me realize that I won't properly maintain the project - so I'm taking this entry out again, deactivate the project's issue section and put a disclaimer in my readme.
=> Remove Reconciler entry

entity-framework/core/modeling/inheritance.md, entity-framework/core/modeling/keyless-entity-types.md, entity-framework/core/modeling/relational/inheritance.md, entity-framework/core/modeling/table-splitting.md, samples/core/DbContextPooling/Program.cs, samples/core/Modeling/FluentAPI/DefaultDiscriminator.cs, samples/core/Modeling/FluentAPI/NonShadowDiscriminator.cs, samples/core/Modeling/FluentAPI/SharedTPHColumns.cs
=> Add documentation for mapping two properties to the same column when using TPH

entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md
=> Fix typo in 'ChangedTracker' to 'ChangeTracker'

entity-framework/core/querying/filters.md
=> filter by navigation properties not a limitation

entity-framework/core/modeling/spatial.md
=> Document PROJ workarounds

entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md, entity-framework/toc.yml
I went through the enhancements already closed-fixed in 5.0 and added anything "Quite Interesting" to the doc. The plan is to update this for each prerelease.
=> What's New in EF Core 5.0

entity-framework/ef6/fundamentals/relationships.md
Related to https://github.com/dotnet/docs/pull/17018
=> Oxford comma

samples/core/Saving/Basics/Sample.cs
example.com is for use in illustrative examples in documents. but sample.com is a real domain
=> Use example.com instead of sample.com

CONTRIBUTING.md, entity-framework/core/get-started/index.md, entity-framework/core/miscellaneous/logging.md, entity-framework/core/miscellaneous/testing/in-memory.md, entity-framework/core/miscellaneous/testing/sqlite.md, entity-framework/core/modeling/data-seeding.md, entity-framework/core/modeling/dynamic-model.md, entity-framework/core/modeling/index.md, entity-framework/core/modeling/keyless-entity-types.md, entity-framework/core/modeling/owned-entities.md, entity-framework/core/modeling/table-splitting.md, entity-framework/core/providers/cosmos/index.md, entity-framework/core/providers/writing-a-provider.md, entity-framework/core/querying/client-eval.md, entity-framework/core/querying/complex-query-operators.md, entity-framework/core/querying/filters.md, entity-framework/core/querying/index.md, entity-framework/core/querying/raw-sql.md, entity-framework/core/querying/related-data.md, entity-framework/core/querying/tracking.md, entity-framework/core/saving/basic.md, entity-framework/core/saving/cascade-delete.md, entity-framework/core/saving/concurrency.md, entity-framework/core/saving/disconnected-entities.md, entity-framework/core/saving/explicit-values-generated-properties.md, entity-framework/core/saving/related-data.md, entity-framework/core/saving/transactions.md, entity-framework/core/what-is-new/ef-core-5.0/plan.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md, entity-framework/ef6/resources/contribute.md
Replace occurrences of *aspnet/EntityFramework.Docs* with *dotnet/EntityFramework.Docs*.
=> Update repo org. references

samples/core/Modeling/FluentAPI/IndexFilter.cs
Remove unwanted #endregion that cause Build error
=> Remove unwanted #endregion that cause Build error

entity-framework/ef6/get-started.md
Corrected a sentence's grammar.
=> Typo Correction

entity-framework/core/querying/how-query-works.md
=> Update no-tracking info in "How queries work?"

entity-framework/ef6/fundamentals/async.md, entity-framework/ef6/fundamentals/connection-resiliency/commit-failures.md, entity-framework/ef6/fundamentals/performance/perf-whitepaper.md, entity-framework/ef6/fundamentals/testing/testability-article.md, entity-framework/ef6/resources/blogs.md
=> Fix some broken blog links

entity-framework/core/modeling/keyless-entity-types.md, samples/core/Modeling/DataAnnotations/Keyless.cs, samples/core/Modeling/FluentAPI/Keyless.cs
Document the Keyless attribute.
Fixes #2186
=> Fix for 2186. Document Keyless Attribute

entity-framework/core/extensions/index.md
=> Add more extensions

entity-framework/breadcrumb/toc.yml
=> Publish to live

entity-framework/core/extensions/index.md
This PR updates the Extensions page so it reflects the support for EF Core 3 by LLBLGen Pro.
=> Updated LLBLGen Pro extension section for support for EF Core 3

entity-framework/core/extensions/index.md, entity-framework/core/modeling/backing-field.md, entity-framework/core/modeling/keyless-entity-types.md, entity-framework/core/what-is-new/ef-core-3.0/index.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md, entity-framework/ef6/modeling/code-first/migrations/teams.md, entity-framework/index.yml
=>  Merge to live 4/22

entity-framework/core/managing-schemas/migrations/index.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md
Further fixes for #2303 and #2337 . Updating per comment that came in after merge for #2303, plus updating the whats-new page to reference the previous changes.
=> Updating WhatsNew page for issues 2303 and 2337.

entity-framework/core/what-is-new/ef-core-2.0.md
Found just a couple of grammar errors that require fixing.
=> Grammar fixes

entity-framework/core/modeling/owned-entities.md, entity-framework/core/modeling/relationships.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md, samples/core/Modeling/FluentAPI/FluentAPI.csproj, samples/core/Modeling/FluentAPI/Relationships/NavigationConfiguration.cs, samples/core/Modeling/OwnedEntities/OwnedEntities.csproj, samples/core/Modeling/OwnedEntities/OwnedEntityContext.cs
Fixes #2302 . Document the Navigation() fluent API.
=> Fix for 2302. Document Navigation() fluent API.

entity-framework/core/miscellaneous/connection-strings.md
See #1900. Removing unneeded parts of links.
=> Making links more relative.

entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md
We are light on features for preview 4.
I have not included any of the collation support since the last part of that is in preview 5. (Yes, we should have pulled it in to 4.)
Also, I would like to include examples of better translation exception messages, but I'm having trouble finding them.
=> Adding preview 4 features

entity-framework/core/miscellaneous/testing/index.md
=> Specifically mention no raw SQL for InMemory

entity-framework/core/modeling/relationships.md
I noticed a couple of minor errors when reading through this topic.
=> Fix [!NOTE] markdown and double 'the'

entity-framework/core/modeling/entity-properties.md, samples/core/Modeling/FluentAPI/PrecisionAndScale.cs
Fixes #527. Documenting the `HasPrecision()` API.
=> Fix for issue 527 - Precision and Scale.

entity-framework/core/querying/filters.md
Update `reqiured` -> `required`
=> Fix a minor typo in Query Filters doc

entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md
Added a missing word to the "Flow arguments into IDesignTimeDbContextFactory" section.
=> Missing word

entity-framework/core/extensions/index.md
An implementation for soft deleting entities for EntityFramework Core.
=> add EFCore.SoftDelete

entity-framework/core/providers/sqlite/limitations.md
=> Update SQLite Limitations for 5.0

entity-framework/index.yml
* Update index.yml
Fix link to WinForms and refresh link to WPF.
=> Update index.yml (#2554)

entity-framework/ef6/modeling/code-first/data-annotations.md
Updated code formatting in line with guidance from https://docs.microsoft.com/en-us/style-guide/developer-content/formatting-developer-text-elements
=> Updated code formatting

entity-framework/core/providers/sql-server/index.md, entity-framework/core/providers/sql-server/indexes.md, entity-framework/toc.yml, samples/core/SqlServer/Indexes/Blog.cs, samples/core/SqlServer/Indexes/ClusteredIndexContext.cs, samples/core/SqlServer/Indexes/IndexFillFactorContext.cs, samples/core/SqlServer/Indexes/IndexOnlineContext.cs, samples/core/SqlServer/SqlServer.csproj
=> Add docs on SQL Server-specific index config

entity-framework/core/get-started/wpf.md, entity-framework/core/managing-schemas/index.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md, entity-framework/ef6/fundamentals/connection-resiliency/commit-failures.md, entity-framework/ef6/fundamentals/databinding/winforms.md, entity-framework/ef6/fundamentals/databinding/wpf.md, entity-framework/ef6/fundamentals/disconnected-entities/index.md, entity-framework/ef6/fundamentals/install.md, entity-framework/ef6/fundamentals/testing/testability-article.md, entity-framework/efcore-and-ef6/index.md, entity-framework/index.yml
=> Clean up links (part 1)

entity-framework/core/miscellaneous/async.md
=> Add note on cancellation tokens

entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
=> Document defining query breaking change

entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/miscellaneous/cli/powershell.md
Resolves #2498, fixes #2543, resolves #2587, fixes dotnet/efcore#18780
=> Tools: Document new commands and options

entity-framework/core/miscellaneous/cli/dotnet.md, entity-framework/core/what-is-new/ef-core-3.x/breaking-changes.md
=> Link to tool manifest docs

entity-framework/core/querying/related-data/eager.md, samples/core/Querying/RelatedData/Sample.cs
Note - this is just raw edited in Github, have not verified locally that this will build and that the link will actually work. Hence draft pull request.
=> Wrong code sample for AsSplitQuery/AsSingleQuery

README.md
=> easier way to edit docs

entity-framework/core/providers/cosmos/index.md, entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md, samples/core/Cosmos/Cosmos.csproj, samples/core/Cosmos/ModelBuilding/OptionsContext.cs
=> Add a sample for the new Cosmos options

entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
=> Document pluralizer breaking change

samples/core/Xamarin/EFGetStarted.Android/EFGetStarted.Android.csproj, samples/core/Xamarin/EFGetStarted.Android/Resources/Resource.designer.cs, samples/core/Xamarin/EFGetStarted.iOS/EFGetStarted.iOS.csproj, samples/core/Xamarin/EFGetStarted/EFGetStarted.csproj
Fixing issue from: https://github.com/dotnet/efcore/issues/22559
The iOS interpreter needs to be on for EF Core to work properly on device while in release mode.
=> updating nugets & adding ios interpreter

entity-framework/core/modeling/owned-entities.md, entity-framework/core/modeling/relationships.md, samples/core/Modeling/OwnedEntities/OwnedEntities.csproj, samples/core/Modeling/OwnedEntities/OwnedEntityContext.cs
=> Add documentation for required dependents

entity-framework/core/modeling/entity-types.md, samples/core/Modeling/FluentAPI/ViewNameAndSchema.cs
=> Add documentation for view mapping.

entity-framework/core/providers/cosmos/functions.md, entity-framework/toc.yml
=> Document Cosmos function mappings

entity-framework/core/modeling/entity-types.md, samples/core/Modeling/FluentAPI/TableExcludeFromMigrations.cs
=> Add documentation for excluding tables from migrations

entity-framework/core/modeling/entity-types.md, entity-framework/core/modeling/inheritance.md, entity-framework/core/modeling/relationships.md, entity-framework/core/providers/cosmos/index.md, samples/core/Cosmos/ModelBuilding/Distributor.cs, samples/core/Cosmos/ModelBuilding/OrderContext.cs, samples/core/Cosmos/ModelBuilding/Sample.cs
=> Add documentation for Cosmos ETag configuration.

entity-framework/core/modeling/shadow-properties.md, entity-framework/toc.yml, samples/core/Modeling/FluentAPI/SharedType.cs
=> Add documentation for property bag entity types.

entity-framework/core/providers/sql-server/functions.md, entity-framework/core/providers/sql-server/spatial.md, entity-framework/core/providers/sqlite/functions.md, entity-framework/toc.yml
=> Document SQL Server function mappings

.github/workflows/build-samples.yml
Also includes the CI config itself to check when that is changed
=> chore: Only build samples if files are changed

entity-framework/core/modeling/index.md, samples/core/Modeling/FluentAPI/EntityTypeConfiguration.cs
=> Add documentation for IEntityTypeConfiguration

entity-framework/core/miscellaneous/nullable-reference-types.md, entity-framework/core/modeling/entity-properties.md, samples/core/Miscellaneous/NullableReferenceTypes/Customer.cs, samples/core/Miscellaneous/NullableReferenceTypes/CustomerWithConstructorBinding.cs, samples/core/Miscellaneous/NullableReferenceTypes/CustomerWithWarning.cs
=> Tweak NRT guidance

entity-framework/core/providers/cosmos/index.md, entity-framework/core/providers/cosmos/limitations.md, samples/core/Cosmos/ModelBuilding/Sample.cs
=> Add documentation for WithPartitionKey

entity-framework/core/modeling/entity-types.md, entity-framework/core/modeling/keyless-entity-types.md, samples/core/Miscellaneous/Testing/BusinessLogic/BlogService.cs, samples/core/Miscellaneous/Testing/BusinessLogic/BloggingContext.cs, samples/core/Miscellaneous/Testing/BusinessLogic/BusinessLogic.csproj, samples/core/Miscellaneous/Testing/BusinessLogic/UrlResource.cs, samples/core/Miscellaneous/Testing/TestProject/InMemory/BlogServiceTests.cs, samples/core/Miscellaneous/Testing/TestProject/SQLite/BlogServiceTests.cs, samples/core/Miscellaneous/Testing/TestProject/TestProject.csproj
Fixes #1223
Fixes #1850
Fixes #898
=> Add a defining query test for a view-mapped entity type

.markdownlint.json, .vscode/settings.json, entity-framework/core/what-is-new/ef-core-3.x/breaking-changes.md, entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
Keep the linter happy at all costs
=> Replace bold with headings in breaking changes pages

entity-framework/core/querying/related-data/eager.md, entity-framework/core/querying/single-split-queries.md, entity-framework/toc.yml
=> Split single/split query in it's own page

entity-framework/core/miscellaneous/cli/dbcontext-creation.md, entity-framework/core/miscellaneous/cli/services.md, samples/core/Miscellaneous/CommandLine/ApplicationService.cs, samples/core/Miscellaneous/CommandLine/BloggingContextFactory.cs, samples/core/Miscellaneous/CommandLine/CommandLine.csproj, samples/core/Miscellaneous/CommandLine/CustomTools.cs, samples/core/Miscellaneous/CommandLine/DesignTimeServices.cs, samples/core/Samples.sln, samples/core/Schemas/Migrations/MigrationTableNameContext.cs, samples/core/Schemas/Migrations/Migrations.csproj, samples/core/Schemas/Migrations/MyHistoryRepository.cs
Also found some orphaned cs files.
Resolves #503
=> Document design-time services

entity-framework/core/modeling/generated-properties.md, samples/core/Modeling/FluentAPI/ComputedColumn.cs
=> Document new support for virtual/stored computed columns

entity-framework/core/what-is-new/ef-core-3.x/breaking-changes.md
=> Update breaking change on TFM in EF Core 3.1

entity-framework/core/extensions/index.md
Lets you write `.AddConfigurationManager()` and `"Name=MyConnection"` instead of `ConfigurationManager.ConnectionStrings["MyConnection"]` 😄
=> Add EntityFrameworkCore.ConfigurationManager extension

entity-framework/core/managing-schemas/migrations/index.md, entity-framework/core/miscellaneous/collations-and-case-sensitivity.md, entity-framework/core/modeling/relationships.md, entity-framework/core/modeling/spatial.md
As discussed, this adds some links to EF community standup videos from relevant doc pages.
=> Add links to some community standup sessions

entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
=> Document two breaking changes for EF Core 5.0

entity-framework/core/querying/client-eval.md
=> Add a note about IX-Async in client eval

entity-framework/core/querying/how-query-works.md, entity-framework/core/querying/tracking.md, samples/core/Querying/Tracking/Program.cs
=> Update notracking docs for identity resolution

entity-framework/core/modeling/inheritance.md, samples/core/Modeling/FluentAPI/DiscriminatorMappingIncomplete.cs
=> Add documentation for complete discriminator mapping

entity-framework/core/modeling/relationships.md
=> Fix many-to-many SQL

entity-framework/core/extensions/index.md
Remove archived extension.
fixes #2896
=> Update with support for EF Core 5.

entity-framework/core/cli/index.md
=> Add clarity to Entity Framework Core tools reference page

samples/core/Saving/Basics/Sample.cs, samples/core/Saving/CascadeDelete/Sample.cs, samples/core/Saving/Concurrency/Sample.cs, samples/core/Saving/Disconnected/Sample.cs, samples/core/Saving/ExplicitValuesGenerateProperties/Sample.cs, samples/core/Saving/Program.cs, samples/core/Saving/RelatedData/Sample.cs, samples/core/Saving/Transactions/AmbientTransaction.cs, samples/core/Saving/Transactions/CommitableTransaction.cs, samples/core/Saving/Transactions/ControllingTransaction.cs, samples/core/Saving/Transactions/ExternalDbTransaction.cs, samples/core/Saving/Transactions/ManagingSavepoints.cs, samples/core/Saving/Transactions/SharingTransaction.cs
=> Revert making saving samples async

entity-framework/core/providers/sql-server/indexes.md
=> Add note on clustered indexes being one-per-table

entity-framework/core/modeling/indexes.md, samples/core/Modeling/DataAnnotations/Index.cs, samples/core/Modeling/DataAnnotations/IndexComposite.cs, samples/core/Modeling/DataAnnotations/IndexName.cs, samples/core/Modeling/DataAnnotations/IndexUnique.cs
=> Document index data annotation 

entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md
=> Added breaking change for required decimal facets

entity-framework/core/index.md
Pascal case should be used in the correct spelling.
=> Fix incorrect spelling

samples/core/Miscellaneous/Testing/BusinessLogic/BusinessLogic.csproj, samples/core/Miscellaneous/Testing/ItemsWebApi/ItemsWebApi/ItemsWebApi.csproj, samples/core/Miscellaneous/Testing/ItemsWebApi/SharedDatabaseTests/SharedDatabaseTests.csproj, samples/core/Miscellaneous/Testing/ItemsWebApi/Tests/Tests.csproj, samples/core/Miscellaneous/Testing/TestProject/TestProject.csproj
move testing samples to ef5 and net5
=> Update dependencies in samples

samples/core/ChangeTracking/ChangeTrackingInEFCore/ExplicitKeysSamples.cs, samples/core/ChangeTracking/ChangeTrackingInEFCore/GeneratedKeysSamples.cs, samples/core/Miscellaneous/Events/Program.cs
=> Removed unnecessary cast to object

entity-framework/core/change-tracking/explicit-tracking.md, entity-framework/core/modeling/value-conversions.md
=> Remove duplicate code blocks

entity-framework/core/change-tracking/explicit-tracking.md, entity-framework/core/change-tracking/index.md, entity-framework/core/change-tracking/relationship-changes.md
Small changes like this is fine right?
=> Fix small typo

entity-framework/core/cli/dbcontext-creation.md
=> Update dbcontext-creation.md (Issue 3064)

entity-framework/ef6/fundamentals/performance/pre-generated-views.md, entity-framework/ef6/saving/change-tracking/property-values.md
=> Remove backslashes in EF6 docs

entity-framework/core/modeling/spatial.md
=> Update spatial docs to reference ProjNet not ProjNet4GeoAPI

entity-framework/core/extensions/index.md
=> Moved supported databases to the description

entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md
=> Fix what's new link to filtered include

entity-framework/core/managing-schemas/migrations/managing.md
=> Reword to avoid double negative

entity-framework/core/cli/dbcontext-creation.md, entity-framework/core/what-is-new/nuget-packages.md
Replace text with XREF for `IDesignTimeDbContextFactory<TContext>`
=> Minor changes in dbcontext-creation.md

entity-framework/core/extensions/index.md
Added [EFCoreAuditing](https://github.com/OKTAYKIR/EFCoreAuditing)
=> Added EFCoreAuditing

entity-framework/core/saving/transactions.md
=> Update .NET Core version known to not support distributed transactions

entity-framework/core/cli/dotnet.md
=> Correct remove migrations docs

entity-framework/core/extensions/index.md
=> Add EntityFrameworkCore.FSharp

entity-framework/core/providers/cosmos/index.md, samples/core/Cosmos/ModelBuilding/Sample.cs
=> Fix mis-aligned highlight

entity-framework/core/querying/filters.md
=> Fix link to samples

entity-framework/core/what-is-new/ef-core-6.0/whatsnew.md
=> Fix Sqlite ToString example in 6.0 what's new

entity-framework/core/saving/cascade-delete.md
=> Correct blog/post confusion

entity-framework/core/extensions/index.md
=> Add EntityFrameworkCore.VisualBasic

entity-framework/core/modeling/entity-types.md
This PR primarily seeks to fix the "`BlogWithMultiplePost`" typo. I made a few other changes to give the PR more weight.
=> Spelling and grammar fixes

entity-framework/core/dbcontext-configuration/index.md
There was an extra left parenthesis with no matching right one, so I removed it.
=> Removed extra parenthesis

entity-framework/core/managing-schemas/migrations/index.md
Addresses [issue I created](https://github.com/dotnet/EntityFramework.Docs/issues/3316)
=> Fix word order typo

entity-framework/core/saving/concurrency.md
=> Update concurrency.md with link to sample

.github/workflows/build-samples.yml, entity-framework/core/what-is-new/ef-core-6.0/plan.md, entity-framework/core/what-is-new/index.md, samples/core/Miscellaneous/NewInEFCore6/.config/dotnet-tools.json, samples/core/Miscellaneous/NewInEFCore6/ArrayParametersSample.cs, samples/core/Miscellaneous/NewInEFCore6/BoolToStringTranslationSample.cs, samples/core/Miscellaneous/NewInEFCore6/ContainsFreeTextSample.cs, samples/core/Miscellaneous/NewInEFCore6/DbContextFactoryHandlesTwoConstructorsSample.cs, samples/core/Miscellaneous/NewInEFCore6/InMemoryRequiredPropertiesSample.cs, samples/core/Miscellaneous/NewInEFCore6/MathFTranslationSample.cs, samples/core/Miscellaneous/NewInEFCore6/NewInEFCore6.csproj, samples/core/Miscellaneous/NewInEFCore6/OptionalDependentsSample.cs, samples/core/Miscellaneous/NewInEFCore6/PreConventionModelConfigurationSample.cs, samples/core/Miscellaneous/NewInEFCore6/Program.cs, samples/core/Miscellaneous/NewInEFCore6/PublicPooledDbContextFactorySample.cs, samples/core/Miscellaneous/NewInEFCore6/ScaffoldNullableReferenceTypesSample.cs, samples/core/Miscellaneous/NewInEFCore6/SplitQuerySample.cs, samples/core/Miscellaneous/NewInEFCore6/SubstringTranslationSample.cs, samples/core/Miscellaneous/NewInEFCore6/TagWithFileAndLineSample.cs, samples/core/Miscellaneous/NewInEFCore6/TemporaryValuesSample.cs, samples/core/Miscellaneous/NewInEFCore6/TrailingUnderscoresSample.cs
Docs for the samples will follow later; I wanted to play with things while we still have time to make changes.
Also some plan/release updates
=> Add samples for 6.0 features

entity-framework/core/modeling/inheritance.md
=> Correct blob/blog typo

entity-framework/core/extensions/index.md
Both now have compatible versions available on nuget
=> Updated compatibility of 2 projects to include EF Core 6

entity-framework/core/extensions/index.md
Adding the EFCore.QueryFilterBuilder to the Entity Framework Extensions list.
=> EFCore.QueryFilterBuilder added to extensions list

entity-framework/core/querying/related-data/lazy.md
=> Added missing "without"

entity-framework/core/performance/advanced-performance-topics.md, entity-framework/core/providers/sql-server/columns.md, entity-framework/core/what-is-new/ef-core-6.0/breaking-changes.md, samples/core/Benchmarks/Benchmarks.csproj, samples/core/Benchmarks/ContextPooling.cs, samples/core/Performance/Performance.csproj, samples/core/Performance/PooledBloggingContext.cs, samples/core/Performance/Program.cs
=> Improvements to context pooling docs

entity-framework/core/what-is-new/ef-core-6.0/breaking-changes.md
=> Document snapshot model initialization breaking change

entity-framework/core/modeling/owned-entities.md
=> Add note on Cosmos in the owned types section 

samples/core/Saving/CascadeDelete/BloggingContext.cs, samples/core/Saving/Saving.csproj
=> Upgrade Saving sample to 6.0.0

entity-framework/core/extensions/index.md
I've been publishing packages like crazy over here!
=> Update some extension versions

entity-framework/core/querying/related-data/eager.md, entity-framework/core/querying/related-data/explicit.md, samples/core/Querying/RelatedData/Blog.cs, samples/core/Querying/RelatedData/BloggingContext.cs, samples/core/Querying/RelatedData/ColorScheme.cs, samples/core/Querying/RelatedData/Program.cs, samples/core/Querying/RelatedData/Theme.cs
=> Document AutoInclude

entity-framework/core/what-is-new/ef-core-6.0/whatsnew.md, samples/core/Miscellaneous/NewInEFCore6/RandomFunctionSample.cs
=> Fixes to 6.0 what's new page

entity-framework/core/cli/powershell.md, entity-framework/core/modeling/data-seeding.md, samples/core/Schemas/Migrations/CustomOperation.cs, samples/core/Schemas/Migrations/CustomOperationMultiSql.cs, samples/core/Schemas/Migrations/CustomOperationSql.cs, samples/core/Spatial/Projections/GeometryExtensions.cs, samples/core/Spatial/SqlServer/Models/City.cs, samples/core/Spatial/SqlServer/Models/Country.cs
Fixes #2967, fixes #3086, fixes #3114
=> Fix some docs bugs

entity-framework/core/extensions/index.md
Added EntityCloner.Microsoft.EntityFrameworkCore
=> Added EntityCloner.Microsoft.EntityFrameworkCore

entity-framework/core/modeling/relationships.md
=> Relationships: typos: can not, many to many

entity-framework/core/logging-events-diagnostics/diagnostic-listeners.md, entity-framework/core/what-is-new/ef-core-2.0/upgrade.md
We should avoid this kind of links in first place.
=> Update some links

samples/core/SqlServer/ValueGeneration/ExplicitIdentityValues.cs
Also this code is never triggered from the Main(). Not sure if this is by design.
=> Fix command execution on wrong table

samples/core/WPF/GetStartedWPF/GetStartedWPF/ProductContext.cs
remove redundant code in the  documentation.
=> Clean OnConfiguring Method

entity-framework/core/modeling/value-conversions.md
=> Fix grammar typo on value conversions page 

entity-framework/core/querying/single-split-queries.md
=> Amend split query note on EF Core versions

entity-framework/core/extensions/index.md
In recent version of EFCore.SoftDelete (1.3.x), I added dotnet 6 support.
=> Update supported versions of EFCore for EFCore.SoftDelete package.

.openpublishing.redirection.json, entity-framework/core/testing/choosing-a-testing-strategy.md, entity-framework/toc.yml
=> Add missing testing page to TOC

entity-framework/core/modeling/shadow-properties.md
The value and state of these properties is maintained => The value and state of these properties are maintained
=> Fix Grammar

entity-framework/core/saving/transactions.md
=> Add note on user transactions and retrying strategies

samples/core/Querying/ComplexQuery/Program.cs
=> Fix JOINs in examples

entity-framework/core/querying/user-defined-function-mapping.md
solves #3729
relative comment: https://github.com/dotnet/efcore/issues/23408#issuecomment-1031877250
=> Remove warning about #23408

.openpublishing.publish.config.json
=> Merge live to main

entity-framework/ef6/fundamentals/logging-and-interception.md
=> Remove sync-over-async in EF6 code sample

.github/workflows/markdownlint.yml, .markdownlint.json
=> Suppres MarkdownLinkt rule MD051

entity-framework/core/extensions/index.md
As per this suggestion: https://github.com/dotnet/efcore/issues/12747#issuecomment-1192517531
=> Add Zomp EF Core Extensions

entity-framework/core/modeling/indexes.md, samples/NuGet.Config, samples/core/Modeling/IndexesAndConstraints/DataAnnotations/IndexDescending.cs, samples/core/Modeling/IndexesAndConstraints/DataAnnotations/IndexDescendingAscending.cs, samples/core/Modeling/IndexesAndConstraints/FluentAPI/IndexDescending.cs, samples/core/Modeling/IndexesAndConstraints/FluentAPI/IndexDescendingAscending.cs, samples/core/Modeling/IndexesAndConstraints/IndexesAndConstraints.csproj
=> Document index sort ordering

entity-framework/core/extensions/index.md
Add Ainoraz.EFCore.IncludeBuilder extension.
=> Add Ainoraz.EFCore.IncludeBuilder Extension

samples/core/Miscellaneous/NewInEFCore7/DocumentsContextStoredProcedures.cs
See https://github.com/dotnet/efcore/issues/29135
=> Fix sproc sample around concurrency token management

entity-framework/core/what-is-new/ef-core-5.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-6.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md
Fixes #3915
Fixes #4024
Fixes #3851
Fixes #3663
Supersedes #4016
=> EF Core 5.0/6.0 breaking change updates

samples/core/Querying/Pagination/Program.cs, samples/core/Querying/SqlQueries/Program.cs
=> Fix some sample issues

entity-framework/core/modeling/table-splitting.md, entity-framework/core/what-is-new/ef-core-7.0/whatsnew.md, entity-framework/toc.yml, samples/core/Miscellaneous/NewInEFCore7/ModelBuildingSample.cs
=> Document entity splitting

entity-framework/core/modeling/keys.md
=> Add note on [PrimaryKey] having been introduced in EF 7

entity-framework/core/saving/transactions.md
=> Update compat note for distributed transactions

entity-framework/core/querying/single-split-queries.md
Noticed these right after merging...
=> Some minor fixups to #4201

entity-framework/core/extensions/index.md
Thanks to Brice for publishing v7
=> EFCore.VisualBasic now supports EF7

entity-framework/core/what-is-new/ef-core-8.0/breaking-changes.md
=> Fixing breaking-changes.md typo

entity-framework/core/providers/cosmos/functions.md, entity-framework/core/providers/cosmos/index.md, entity-framework/core/providers/cosmos/limitations.md, entity-framework/core/what-is-new/ef-core-6.0/whatsnew.md, samples/core/Miscellaneous/NewInEFCore6.Cosmos/CosmosModelConfigurationSample.cs, samples/core/Miscellaneous/NewInEFCore6.Cosmos/CosmosQueriesSample.cs, samples/core/Miscellaneous/NewInEFCore6.Cosmos/Program.cs
Fixes #4017
Fixes #3730
Fixes #3555
Part of #2325
=> Cosmos updates

entity-framework/core/managing-schemas/scaffolding/index.md, entity-framework/core/miscellaneous/platforms.md, entity-framework/core/providers/cosmos/functions.md, entity-framework/core/providers/sql-server/value-generation.md, entity-framework/core/what-is-new/ef-core-6.0/whatsnew.md, entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md, entity-framework/core/what-is-new/index.md
Fixes #3760
Fixes #4274
Fixes #1914
Fixes #1090
=> Updates to scaffolding docs

entity-framework/core/saving/transactions.md
=> Add note on TransactionScope on supporting async

entity-framework/core/performance/efficient-updating.md, entity-framework/core/saving/basic.md, entity-framework/core/saving/execute-insert-update-delete.md, entity-framework/core/saving/index.md, entity-framework/core/what-is-new/ef-core-7.0/whatsnew.md, samples/core/Saving/Basics/Sample.cs
=> Documentation on ExecuteUpdate/Delete

entity-framework/core/saving/basic.md
The message below Deleting Data incorrectly referenced DbSet<TEntity>.Add instead of the DbSet<TEntity>.Remove method.
=> Update the message below Deleting Data

entity-framework/core/managing-schemas/migrations/projects.md
=> Add missing slash

entity-framework/core/saving/transactions.md
=> Clarify interation between MARS and Savepoints

entity-framework/core/providers/cosmos/functions.md, entity-framework/core/providers/sql-server/functions.md, entity-framework/core/providers/sqlite/functions.md
This adds translations up to dotnet/efcore@d7fa2be
Part of #4419
=> Add new function mappings in 8.0

entity-framework/core/providers/sql-server/functions.md, entity-framework/core/providers/sql-server/hierarchyid.md, entity-framework/toc.yml
=> Move HierarchyId section from What's New to its own article

entity-framework/core/providers/sql-server/functions.md, entity-framework/core/providers/sqlite/functions.md
=> Document SQLite translation to unhex

entity-framework/core/miscellaneous/plugins.md, entity-framework/toc.yml
=> Document plug-in APIs

entity-framework/index.yml
Per email thread with @kjo-msft
[Internal preview](https://review.learn.microsoft.com/en-us/ef/?branch=pr-en-us-4458)
=> Reposition Training module on overview hub

entity-framework/core/querying/complex-query-operators.md
=> Document client GroupBy

entity-framework/core/cli/dotnet.md, entity-framework/core/managing-schemas/migrations/managing.md
=> Document has-pending-model-changes

entity-framework/core/what-is-new/ef-core-7.0/breaking-changes.md
=> Document 7.0 changes around RETURNING and non-WAL

samples/core/SqlServer/Misc/TriggersContext.cs
Part of https://github.com/dotnet/efcore/issues/31627
=> Update BlankTriggerAddingConvention to not create triggers for non-base TPH types

entity-framework/core/extensions/index.md, entity-framework/core/what-is-new/ef-core-8.0/whatsnew.md
I tested that these will continue to work on 8 without any changes.
=> Update my extensions to 8

entity-framework/core/what-is-new/ef-core-8.0/whatsnew.md
=> Add missing word

entity-framework/core/managing-schemas/migrations/applying.md
=> Added information regarding appsettings.json inclusion in migrations

entity-framework/core/modeling/relationships.md
=> Fix wrong table in relationships page

entity-framework/core/what-is-new/ef-core-8.0/whatsnew.md
Corrected spelling from "colum" to "column"
=> Fixed "colum" typo

entity-framework/core/what-is-new/ef-core-9.0/whatsnew.md
Corrected spelling from "wre" to "were".
=> Fixed typo in whatsnew.md

entity-framework/ef6/what-is-new/index.md
part of https://github.com/dotnet/ef6/issues/2237
=> Update what's new for 6.5

entity-framework/core/what-is-new/ef-core-9.0/breaking-changes.md
See https://github.com/dotnet/efcore/issues/33864
/cc @ranma42
=> Add breaking change note for Unhex() nullability change

entity-framework/ef6/what-is-new/index.md, entity-framework/ef6/what-is-new/microsoft-ef6-sqlserver.md
=> Add MDS provider readme contents to docs

.openpublishing.redirection.json, entity-framework/core/logging-events-diagnostics/metrics.md, entity-framework/core/performance/advanced-performance-topics.md, entity-framework/core/performance/performance-diagnosis.md, entity-framework/core/what-is-new/ef-core-5.0/whatsnew.md, entity-framework/toc.yml
Event counters left as a legacy thing on the bottom.
=> Documentation about metrics

entity-framework/core/modeling/relationships/one-to-many.md
A sentence was grammatically wrong in this document.
https://learn.microsoft.com/en-us/ef/core/modeling/relationships/one-to-many
=> Update one-to-many.md for a small grammar mistake

entity-framework/core/what-is-new/ef-core-9.0/whatsnew.md
=> Fix typo in What's new 9.0

entity-framework/core/what-is-new/ef-core-8.0/breaking-changes.md
Hi there!
I just fixed a typo and added a space where hyphens were right before a word.
=> Fixed typo and added some space

entity-framework/core/logging-events-diagnostics/metrics.md
Changes matching https://github.com/dotnet/efcore/pull/34267.
=> Update docs for OTEL to match efcore#34267.

entity-framework/ef6/modeling/designer/advanced/edmx/csdl-spec.md, entity-framework/ef6/modeling/designer/advanced/edmx/msl-spec.md, entity-framework/ef6/modeling/designer/advanced/edmx/ssdl-spec.md
This came up while reviewing the implementation
=> Add a note about EDMX V1 being deprecated

entity-framework/core/performance/advanced-performance-topics.md, entity-framework/toc.yml, samples/core/Miscellaneous/CommandLine/Properties/launchSettings.json, samples/core/Miscellaneous/ConfiguringDbContext/Properties/launchSettings.json, samples/core/Miscellaneous/Multitenancy/MultiDb/Properties/launchSettings.json, samples/core/Miscellaneous/Multitenancy/SingleDbSingleTable/Properties/launchSettings.json, samples/core/Miscellaneous/NewInEFCore9.CompiledModels/App/App.csproj, samples/core/Miscellaneous/NewInEFCore9.CompiledModels/Model/Model.csproj, samples/core/Miscellaneous/NewInEFCore9.Cosmos/CosmosSyncApisSample.cs, samples/core/Miscellaneous/NewInEFCore9.Cosmos/HierarchicalPartitionKeysSample.cs, samples/core/Miscellaneous/NewInEFCore9.Cosmos/NewInEFCore9.Cosmos.csproj, samples/core/Miscellaneous/NewInEFCore9/NewInEFCore9.csproj, samples/core/Miscellaneous/NewInEFCore9/PrimitiveCollectionsSample.cs, samples/core/Performance/AspNetContextPooling/Properties/launchSettings.json, samples/core/Performance/AspNetContextPoolingWithState/Properties/launchSettings.json, samples/core/Querying/SqlQueries/Program.cs, samples/core/Schemas/ThreeProjectMigrations/WebApplication1/Properties/launchSettings.json, samples/core/Testing/BloggingWebApi/Properties/launchSettings.json
Update title for Advanced Performance Topics
Reference the released rc1
Fix or suppress warnings
=> Add missing page to ToC

entity-framework/core/providers/sql-server/hierarchyid.md
=> Fix incorrect halfling name in HierarchyId example

entity-framework/core/providers/sqlite/limitations.md
=> Add note to SQLite limitations page on concurrency tokens

entity-framework/core/querying/sql-queries.md
=> Correct reference to SqlQuery

entity-framework/core/includes/managed-identities-test-non-production.md, entity-framework/core/miscellaneous/connection-strings.md
Contributes to #4788
[INternal review URL](https://review.learn.microsoft.com/en-us/ef/core/miscellaneous/connection-strings?branch=pr-en-us-4842)
=> ROPC: connections strs and includes

samples/core/Miscellaneous/NewInEFCore9/QuerySample.cs
=> Fix code reference

entity-framework/core/what-is-new/ef-core-10.0/breaking-changes.md, entity-framework/core/what-is-new/ef-core-10.0/whatsnew.md
https://github.com/dotnet/efcore/issues/32018
=> Document ExecuteUpdateAsync lambda change

samples/core/Saving/Transactions/ControllingTransaction.cs, samples/core/Saving/Transactions/ExternalDbTransaction.cs, samples/core/Saving/Transactions/ManagingSavepoints.cs, samples/core/Saving/Transactions/SharingTransaction.cs, samples/core/Testing/BloggingWebApi/Controllers/BloggingController.cs
=> Add async disposal to transactions in samples

entity-framework/core/managing-schemas/migrations/operations.md
See user confusion in https://github.com/npgsql/efcore.pg/issues/3492
=> Qualify note to SQL Server

entity-framework/core/extensions/index.md
This PR adds EntityFrameworkCore.AuditInterceptor to the list of available EF Core extensions.
EntityFrameworkCore.AuditInterceptor is a library that provides seamless auditing capabilities for Entity Framework Core applications.  It automatically tracks entity changes, recording who made the changes and when they occurred through a simple implementation of the IAuditable interface.
Key features:
- Automatic tracking of entity changes (creation, updates)
- Seamless integration with .NET Dependency Injection
- Easy setup through extension methods
- Support for various auditing scenarios
- Compatible with EF Core versions 6-8
The extension is published on [NuGet](https://www.nuget.org/packages/EntityFrameworkCore.AuditInterceptor) and is actively maintained.
=> Add EntityFrameworkCore.AuditInterceptor to EF Core extensions list

entity-framework/core/extensions/index.md
This PR Moves EntityFrameworkCore.AuditInterceptor to Extensions section.
=> EntityFrameworkCore.AuditInterceptor to Extensions section

.github/workflows/markdownlint.yml
see: https://github.com/actions/runner-images/issues/11101
=> update ubuntu image for markdown lint workflow

entity-framework/core/performance/nativeaot-and-precompiled-queries.md
Closes https://github.com/dotnet/EntityFramework.Docs/issues/5006
=> (nativeaot-and-precompiled-queries.md) add warning

entity-framework/core/performance/nativeaot-and-precompiled-queries.md
=> Fixup code fencing issue

entity-framework/toc.yml
~Based on top of https://github.com/dotnet/EntityFramework.Docs/pull/5009~
Adding TOC entry for full-text-search.md file that has been added
~Review the second commit only~
=> Add toc entry for cosmos fts

samples/core/Modeling/Relationships/ManyToMany.cs
Update code snippets to match lambda expressions.
I went ahead with this change because the inline snippets are already updated, e.g. https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships/many-to-many.md?plain=1#L152-L162
Closes #4846
=> update examples to be more clear/correct

entity-framework/core/providers/sql-server/functions.md, entity-framework/core/providers/sqlite/functions.md, entity-framework/core/what-is-new/ef-core-10.0/whatsnew.md
See https://github.com/dotnet/efcore/pull/36189
=> Document new DateOnly.DayNumber translations

entity-framework/core/providers/cosmos/full-text-search.md, entity-framework/core/providers/cosmos/vector-search.md
=> Document Cosmos vector search/FTS being introduced in 10

entity-framework/core/what-is-new/ef-core-10.0/whatsnew.md
See https://github.com/dotnet/efcore/issues/26808
=> Document split query ordering consistency for EF10

entity-framework/core/what-is-new/ef-core-10.0/whatsnew.md
See https://github.com/dotnet/efcore/issues/28766
=> Document ExecuteUpdate support for complex JSON

entity-framework/core/what-is-new/ef-core-10.0/whatsnew.md
To complete our what's new docs ASAP after the rc.1 release, here's the missing release note on complex types.
I'll be working on a more full complex types/JSON docs page a bit later.
Part of #4413
=> What's new notes on complex types
